import { test, expect } from "@playwright/test";
test.beforeEach(async ({ request }) => { expect((await request.post("/api/reset-fixture")).ok()).toBe(true); });
import { mock, open, pair } from "../helpers/mock-scanner-bridge";
test("signed bridge protocol: pairing, profiles, test scan, 100 cards, review, real commit, next batch", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  const state = await mock(page); await open(page); await pair(page);
  const baseline = await (await page.request.get("/api/evidence")).json();
  await page.getByRole("combobox", { name: "Scanner profile" }).selectOption("quality"); await expect(page.getByText(/600 DPI/)).toBeVisible();
  await page.getByRole("button", { name: "Scanner Settings", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "Scanner DPI" })).toHaveValue("600"); await expect(page.getByRole("checkbox", { name: "Duplex", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Test Scan", exact: true }).click(); await expect(page.getByRole("button", { name: "Looks Good", exact: true })).toBeVisible();
  await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "0"); await page.getByRole("button", { name: "Looks Good", exact: true }).click();
  let recognized = 0;
  await page.route("**/api/purchasing/card-photo-scan", async route => { const response = await route.fetch(); const result = await response.json(); recognized++; if (recognized === 100) result.requiresConfirmation = true; await route.fulfill({ response, json: result }); });
  await page.getByRole("button", { name: "Start Live Scanning", exact: true }).click();
  await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "100", { timeout: 120_000 });
  await expect(page.getByRole("button", { name: "Start Live Scanning", exact: true })).toBeDisabled(); await expect(page.getByRole("button", { name: "Scan One", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Resolve 1 Items", exact: true })).toBeEnabled(); await page.getByRole("button", { name: "Resolve 1 Items", exact: true }).click(); await page.getByRole("button", { name: "Confirm", exact: true }).filter({ visible: true }).click();
  expect(state.captures).toBe(101); expect(state.ack).toBe(101);
  await page.getByRole("button", { name: "Commit 100 Cards to Inventory", exact: true }).click(); await expect(page.getByRole("heading", { name: "100 cards added", exact: true })).toBeVisible({ timeout: 30_000 });
  expect(await (await page.request.get("/api/evidence")).json()).toMatchObject({ cards: baseline.cards + 100, positions: baseline.positions + 100, events: baseline.events + 100, batches: baseline.batches + 1, enabled: 0 });
  await expect(page.getByRole("link", { name: "Print Batch Label", exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "Start Next 100", exact: true })).toHaveCount(0); state.hold = true; await page.getByRole("button", { name: "Label printed and batch filed", exact: true }).click(); await page.getByRole("button", { name: "Start Next 100", exact: true }).first().click(); await page.getByRole("button", { name: "Keep destination", exact: true }).click(); await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "0");
  await expect(page.getByRole("combobox", { name: "Installed scanner" })).toHaveValue("opaque-fixture"); expect(errors).toEqual([]);
});
test("remembered scanner, missing device, jam, cancellation and disconnect retain draft", async ({ page }) => {
  const state = await mock(page); await open(page); await pair(page); await page.getByRole("button", { name: "Create Cloud Batch", exact: true }).click(); await page.reload();
  await expect(page.getByRole("combobox", { name: "Installed scanner" })).toHaveValue("opaque-fixture");
  await page.getByRole("button", { name: "Scan One", exact: true }).click(); await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "1"); await expect(page.getByRole("button", { name: "Scan One", exact: true })).toBeEnabled();
  state.fail = "PAPER_JAM"; await page.getByRole("button", { name: "Scan One", exact: true }).click(); await expect(page.getByText(/Paper\/card jam/)).toBeVisible(); state.fail = "";
  state.hold = true; await page.getByRole("button", { name: "Start Live Scanning", exact: true }).click(); await page.getByRole("button", { name: "Cancel Current Scan", exact: true }).click(); await expect(page.getByRole("button", { name: "Scan One", exact: true })).toBeEnabled(); expect(state.cancelled).toBeGreaterThan(0); state.hold = false;
  state.missing = true; await page.getByRole("button", { name: "Refresh Devices", exact: true }).click(); await expect(page.getByText(/Previously selected scanner not found/)).toBeVisible(); await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "1");
  state.missing = false; await page.getByRole("button", { name: "Refresh Devices", exact: true }).click(); await expect(page.getByRole("button", { name: "Scan One", exact: true })).toBeEnabled();
  state.offline = true; await page.getByRole("button", { name: "Scan One", exact: true }).click(); await expect(page.getByText(/not reachable/)).toBeVisible(); await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "1");
});
test("absent and incompatible bridge preserve Upload and CSV", async ({ page }) => {
  const state = await mock(page); state.offline = true; await open(page); await expect(page.getByText("Connect a physical scanner", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Pair this workstation", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Pair this workstation", exact: true })).toBeDisabled();
  await expect(page.getByRole("combobox", { name: "Installed scanner" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Scanner Settings", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Test Scan", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Upload Images", exact: true }).click(); await expect(page.locator('input[type="file"][accept="image/jpeg,image/png,image/webp"]')).toHaveCount(1);
  state.offline = false; state.version = 0; await page.getByRole("button", { name: "Live Scan", exact: true }).click(); await expect(page.getByText("Scanner Bridge update required.", { exact: true })).toBeVisible();
});
test("mobile device selection and settings fit the workstation", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await mock(page); await open(page); await pair(page);
  await page.getByRole("button", { name: "Scanner Settings", exact: true }).click();
  await page.getByRole("combobox", { name: "Scanner DPI" }).selectOption("600");
  await expect(page.getByRole("combobox", { name: "Scanner profile" })).toHaveValue("custom");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("combobox", { name: "Installed scanner" }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: ".playwright-results/scanner-bridge-mobile.png" });
});

test("external-settings backend waits for physical output, previews, cancels and resumes without vendor branches", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  const state = await mock(page); state.external = true; state.hold = true;
  await open(page); await pair(page);
  await expect(page.getByRole("note")).toContainText("press Scan on the iX500");
  await expect(page.getByRole("combobox", { name: "Scanner profile" })).toHaveCount(0);
  await page.getByRole("button", { name: "Scanner Settings", exact: true }).click();
  await expect(page.getByText("Configure the required profile", { exact: false })).toBeVisible();
  await expect(page.getByRole("combobox", { name: "Scanner DPI" })).toHaveCount(0);
  await page.getByRole("button", { name: "Test Scan", exact: true }).click();
  await expect.poll(() => state.captures).toBe(1);
  await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "0");
  state.hold = false;
  await expect(page.getByRole("button", { name: "Looks Good", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Looks Good", exact: true }).click();
  state.hold = true;
  await page.getByRole("button", { name: "Start Live Scanning", exact: true }).click();
  await expect.poll(() => state.captures).toBe(2);
  await page.getByRole("button", { name: "Cancel Current Scan", exact: true }).click();
  await expect(page.getByRole("button", { name: "Scan One", exact: true })).toBeEnabled();
  await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "0");
  state.hold = false;
  await page.getByRole("button", { name: "Scan One", exact: true }).click();
  await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "1");
  await expect.poll(() => state.ack).toBe(2); expect(errors).toEqual([]);
});
