export {
  BINDER_PLATFORM_BACKEND_TABLES,
  binderShareStatusLabel,
  binderSlotLabels,
  buildPhysicalBinderState,
  buildBinderPage,
  buildBinderSpread,
  createBinderSharePayload,
  normalizeBinderShareRequest,
  placementKey,
  revokeBinderSharePayload,
  validateBinderPlacement,
  type BinderShareLink,
  type BinderShareRequest,
  type BinderShareScope,
  type PhysicalBinder,
  type PhysicalBinderCardPlacement,
  type PhysicalBinderPage,
  type PhysicalBinderPocket,
  type PhysicalBinderState,
  type PhysicalBinderSummary,
  type PhysicalBinderSpread,
  type PhysicalBinderVisibility,
  type RawPortfolioBinder,
  type RawPortfolioShare,
} from "../../mobile/services/physical-binder.ts";
