import { Ionicons } from '@expo/vector-icons';
import { PropsWithChildren } from 'react';
import { Pressable, StyleProp, StyleSheet, Text, View, ViewStyle } from 'react-native';
import { brand as B } from '@/constants/brand';

export function Logo({ compact = false }: { compact?: boolean }) {
  return <View style={s.logoRow}><View style={[s.mark, compact && s.markSmall]}><View style={s.markInner}/></View>{!compact && <View><Text style={s.word}>TRADING DOCKS</Text><Text style={s.tag}>COLLECT · KNOW · MOVE</Text></View>}</View>;
}
export function GlassCard({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { return <View style={[s.card, style]}>{children}</View>; }
export function SectionTitle({ title, action }: { title: string; action?: string }) { return <View style={s.sectionRow}><Text style={s.section}>{title}</Text>{action ? <Text style={s.action}>{action}</Text> : null}</View>; }
export function Pill({ text, tone = 'blue' }: { text: string; tone?: 'blue'|'green'|'amber' }) { const bg = tone==='green'?B.green:tone==='amber'?B.amber:B.blue; return <View style={[s.pill,{backgroundColor:bg+'20',borderColor:bg+'55'}]}><View style={[s.dot,{backgroundColor:bg}]}/><Text style={[s.pillText,{color:bg}]}>{text}</Text></View>; }
export function QuickAction({ icon, label, subtitle }: { icon: keyof typeof Ionicons.glyphMap; label: string; subtitle: string }) { return <Pressable style={({pressed})=>[s.quick, pressed && {transform:[{scale:.98}],opacity:.88}]}><View style={s.quickIcon}><Ionicons name={icon} size={21} color={B.cyan}/></View><Text style={s.quickLabel}>{label}</Text><Text style={s.quickSub}>{subtitle}</Text></Pressable>; }
const s=StyleSheet.create({logoRow:{flexDirection:'row',alignItems:'center',gap:12},mark:{width:46,height:46,borderRadius:15,backgroundColor:B.blue,alignItems:'center',justifyContent:'center',shadowColor:B.blue,shadowOpacity:.45,shadowRadius:16,elevation:8},markSmall:{width:40,height:40,borderRadius:13},markInner:{width:20,height:20,borderWidth:4,borderColor:'#fff',borderTopLeftRadius:3,borderBottomRightRadius:3,transform:[{rotate:'45deg'}]},word:{color:B.text,fontSize:14,fontWeight:'900',letterSpacing:1.8},tag:{color:B.muted,fontSize:8,fontWeight:'700',letterSpacing:1.15,marginTop:3},card:{backgroundColor:B.surface,borderColor:B.line,borderWidth:1,borderRadius:24,padding:18},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},section:{color:B.text,fontSize:18,fontWeight:'900',letterSpacing:-.25},action:{color:B.cyan,fontSize:12,fontWeight:'800'},pill:{flexDirection:'row',alignItems:'center',gap:7,borderWidth:1,borderRadius:999,paddingHorizontal:10,paddingVertical:7},dot:{width:6,height:6,borderRadius:4},pillText:{fontSize:10,fontWeight:'900'},quick:{width:'48.3%',backgroundColor:B.surface,borderColor:B.line,borderWidth:1,borderRadius:20,padding:15,minHeight:132},quickIcon:{width:39,height:39,borderRadius:13,backgroundColor:B.blue+'20',alignItems:'center',justifyContent:'center',marginBottom:14},quickLabel:{color:B.text,fontWeight:'900',fontSize:14},quickSub:{color:B.muted,fontSize:11,lineHeight:16,marginTop:5}});
