import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Surface } from '@/components/foundation';
import { color, radius, space, type } from '@/design';
import { useState } from 'react';
const rows=[['Biometric unlock','Use Face ID or device biometrics','finger-print-outline'],['Background sync','Sync saved sessions when a connection returns','cloud-upload-outline'],['Haptic feedback','Tactile confirmation for important actions','phone-portrait-outline']];
export default function Settings(){const [values,setValues]=useState([false,true,true]);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="chevron-back" size={22} color={color.text}/></Pressable><Text style={s.eyebrow}>PREFERENCES</Text><Text style={s.title}>Settings</Text><Text style={s.sub}>Control security, offline behavior, and interaction feedback.</Text><Surface style={s.group}>{rows.map((r,i)=><View key={r[0]} style={[s.row,i<rows.length-1&&s.divider]}><View style={s.icon}><Ionicons name={r[2] as any} size={20} color={color.primaryBright}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{r[0]}</Text><Text style={s.rowSub}>{r[1]}</Text></View><Switch value={values[i]} onValueChange={v=>setValues(cur=>cur.map((x,j)=>j===i?v:x))} trackColor={{false:color.border,true:color.primary}}/></View>)}</Surface><Text style={s.note}>Biometric unlock and background synchronization are foundation controls. Provider-level activation is completed when production credentials and native builds are configured.</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:color.canvas},content:{padding:space.lg,paddingBottom:space.xxl},back:{width:44,height:44,borderRadius:radius.md,backgroundColor:color.surface,borderWidth:1,borderColor:color.border,alignItems:'center',justifyContent:'center'},eyebrow:{...type.label,color:color.primaryBright,marginTop:space.xl},title:{...type.display,color:color.text,marginTop:space.xs},sub:{...type.body,color:color.textSecondary,marginTop:space.sm},group:{marginTop:space.lg,paddingVertical:space.xs},row:{flexDirection:'row',alignItems:'center',gap:space.sm,paddingVertical:space.md},divider:{borderBottomWidth:1,borderBottomColor:color.border},icon:{width:42,height:42,borderRadius:radius.md,backgroundColor:color.primary+'20',alignItems:'center',justifyContent:'center'},rowTitle:{color:color.text,fontSize:14,fontWeight:'900'},rowSub:{...type.caption,color:color.textMuted,marginTop:3},note:{...type.caption,color:color.textMuted,marginTop:space.md,lineHeight:18}});
