"use client";

import { useMemo, useState } from "react";
import { percentLabel, type Standing } from "@/lib/tournament-standings";

export type PublicPairing = { round: number; table: number; player: string; opponent: string; resultStatus: string; };

export function TournamentStandingsPanel({ standings, pairings = [], currentRound, publicView = false }: { standings: Standing[]; pairings?: PublicPairing[]; currentRound: number; publicView?: boolean }) {
  const [query, setQuery] = useState("");
  const visible = useMemo(() => query.trim() ? standings.filter((row) => row.displayName.toLowerCase().includes(query.trim().toLowerCase())) : standings, [query, standings]);
  const pairing = query.trim() ? pairings.find((row) => row.player.toLowerCase().includes(query.trim().toLowerCase())) : null;
  return <section className="mx-auto mt-6 max-w-5xl rounded-[28px] border border-td-ink/[.08] bg-td-surface p-6 text-td-primary sm:p-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-td-accent-text">Tournament standings</p><h2 className="mt-2 text-2xl font-semibold">{currentRound > 0 ? `Round ${currentRound}` : "Registration"}</h2><p className="mt-1 text-sm text-td-muted">{currentRound > 0 ? "Match history is recalculated live after each reported result." : "Standings will appear when the event starts."}</p></div>{currentRound > 0 ? <label className="text-xs text-td-muted">{publicView ? "Find your name" : "Find player"}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search display name" className="mt-1 h-10 w-full rounded-xl border border-td-ink/[.1] bg-td-background px-3 text-sm text-td-primary outline-none sm:w-52" /></label> : null}</div>{pairing ? <div className="mt-4 rounded-xl border border-td-accent/20 bg-td-accent/[.06] p-3 text-sm text-td-secondary">{pairing.player}: Table {pairing.table} vs {pairing.opponent}</div> : null}{currentRound > 0 ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-td-ink/[.08] text-xs uppercase tracking-[.12em] text-td-muted"><tr><th className="px-3 py-3">Rank</th><th className="px-3 py-3">Player</th><th className="px-3 py-3">Pts</th><th className="px-3 py-3">W</th><th className="px-3 py-3">L</th><th className="px-3 py-3">D</th><th className="px-3 py-3">OMW%</th><th className="px-3 py-3">GW%</th><th className="px-3 py-3">OGW%</th></tr></thead><tbody>{visible.map((row) => <tr key={row.playerId} className="border-b border-td-ink/[.06]"><td className="px-3 py-3 font-semibold">{row.rank}</td><td className="px-3 py-3">{row.displayName}{row.playerStatus !== "active" ? <span className="ml-2 text-xs text-amber-200">({row.playerStatus})</span> : null}</td><td className="px-3 py-3 font-semibold">{row.matchPoints}</td><td className="px-3 py-3">{row.matchWins}</td><td className="px-3 py-3">{row.matchLosses}</td><td className="px-3 py-3">{row.matchDraws}</td><td className="px-3 py-3">{percentLabel(row.omw)}</td><td className="px-3 py-3">{percentLabel(row.gw)}</td><td className="px-3 py-3">{percentLabel(row.ogw)}</td></tr>)}</tbody></table></div> : null}</section>;
}
