import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const container='supabase_db_trading-docks-recovery-test';
const state=JSON.parse(execFileSync('docker',['inspect',container],{encoding:'utf8'}))[0];
assert.deepEqual(state.NetworkSettings.Networks,{}); assert.match(state.Config.Image,/supabase\/postgres:17\./);
const database='phase1p_'+Date.now();
const sql=(q,db=database)=>execFileSync('docker',['exec','-i',container,'psql','-U','postgres','-d',db,'-X','-qAt','-v','ON_ERROR_STOP=1'],{input:q,encoding:'utf8',stdio:['pipe','pipe','pipe'],timeout:60000}).trim();
sql(`create database ${database} template collector_removal_rehearsal`,'template1');
try {
 for (const file of ['20260923204804_chaos_scan_albums_v2.sql','20260924000100_chaos_cloud_authority.sql','20260924005111_chaos_legacy_workspace_normalization.sql','20260924013600_cloud_active_workspace_authority.sql','20260925024439_inventory_mutation_idempotency.sql','20260925150035_inventory_lot_command_receipts.sql']) sql(readFileSync('supabase/migrations/'+file,'utf8'));
 const owner=randomUUID(); sql(`insert into auth.users(id,email) values('${owner}','phase1p@example.invalid');update user_preferences set active_workspace_id=(select workspace_id from workspace_members where user_id='${owner}' limit 1) where user_id='${owner}';`);
 const as=q=>`begin;set local role authenticated;select set_config('request.jwt.claim.sub','${owner}',true);${q};commit;`;
 const run=q=>sql(as(q)).split('\n').at(-1);
 const wid=run('select current_inventory_workspace()');
 run(`insert into inventory_items(id,user_id,workspace_id,card_name,quantity,data) values('p-lot','${owner}','${wid}','Synthetic lot',10,'{}')`);
 const removal=(qty,key,reason='Disposition')=>JSON.parse(run(`select remove_inventory_lot_quantity('p-lot',${qty},'${reason}','${key}')`));
 const qty=()=>Number(sql("select quantity from inventory_items where id='p-lot'"));
 const a=removal(3,'A');assert.equal(qty(),7);assert.equal(a.operationId,'A');assert.equal(a.user_id,owner);assert.equal(a.workspace_id,wid);
 assert.deepEqual(removal(3,'A'),a);assert.equal(qty(),7);removal(2,'B');assert.equal(qty(),5);assert.deepEqual(removal(3,'A'),a);assert.equal(qty(),5);
 assert.throws(()=>removal(2,'A'),/IDEMPOTENCY_CONFLICT/);assert.throws(()=>removal(3,'A','Different reason'),/IDEMPOTENCY_CONFLICT/);assert.equal(qty(),5);
 assert.equal(sql("select count(*)||':'||sum(quantity_change) from inventory_events where inventory_item_id='p-lot'"),'2:-5');
 const box=randomUUID();run(`insert into inventory_locations(id,user_id,name) values('${box}','${owner}','Synthetic box')`);
 const move=()=>JSON.parse(run(`select move_inventory_lot_quantity('p-lot',2,'${box}','MOVE')`));
 const m=move();assert.equal(qty(),3);assert.deepEqual(move(),m);assert.equal(qty(),3);
 assert.equal(sql(`select quantity from inventory_items where id='${m.destinationItemId}'`),'2');
 assert.throws(()=>run(`select move_inventory_lot_quantity('p-lot',1,'${box}','MOVE')`),/IDEMPOTENCY_CONFLICT/);
 const fresh=randomUUID(), key=randomUUID();
 const row={id:fresh,user_id:owner,workspace_id:wid,card_name:'Synthetic append',quantity:3,inventory_value:30,asking_price:11.99,data:{}};
 const append=r=>JSON.parse(run(`select to_jsonb(create_inventory_item_with_event('${JSON.stringify(r)}'::jsonb,'csv_import','${key}','inventory_append','manifest'))`));
 const receipt=append(row); assert.equal(Number(receipt.asking_price),11.99); assert.deepEqual(append(row),receipt);
 run(`select apply_collector_inventory_mutation('${fresh}','quantity',7,null,null,null,'later-edit','manual')`);
 assert.deepEqual(append(row),receipt); assert.equal(sql(`select quantity from inventory_items where id='${fresh}'`),'7');
 assert.throws(()=>append({...row,quantity:4}),/IDEMPOTENCY_CONFLICT/);
 assert.equal(sql(`select count(*) from inventory_events where inventory_item_id='${fresh}' and source='csv_import'`),'1');
 console.log('PASS append RPC: explicit asking preserved; lost-response-equivalent retry; stale append preserves later quantity; changed snapshot child conflicts');
 console.log('PASS lot RPC: 10→7, replay→7, 7→5, stale replay→5; changed quantity/reason conflict; event deltas; split move duplicate receipt');
} finally { sql(`drop database ${database}`,'template1'); }
