begin read only; set local search_path=public;
select jsonb_build_object(
'schemas',(select jsonb_agg(nspname) from pg_namespace where nspname in('public','pos_private','inventory_private')),
'tables',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'rls',c.relrowsecurity,'force',c.relforcerowsecurity,'acl',c.relacl::text,'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped))) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('public','pos_private','inventory_private') and c.relkind='r'),
'functions',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'identity',p.oid::regprocedure::text,'ddl',pg_get_functiondef(p.oid),'acl',p.proacl::text,'owner',pg_get_userbyid(p.proowner))) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('public','pos_private','inventory_private') and p.prokind='f'),
'constraints',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',k.conname,'type',k.contype,'ddl',pg_get_constraintdef(k.oid,true),'valid',k.convalidated)) from pg_constraint k join pg_class c on c.oid=k.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in('public','pos_private','inventory_private')),
'indexes',(select jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'name',indexname,'ddl',indexdef)) from pg_indexes where schemaname in('public','pos_private','inventory_private')),
'policies',(select jsonb_agg(to_jsonb(p)) from pg_policies p where schemaname in('public','pos_private','inventory_private')),
'triggers',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'ddl',pg_get_triggerdef(t.oid),'enabled',t.tgenabled)) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in('public','pos_private','inventory_private') and not t.tgisinternal),
'enums',(select jsonb_agg(x) from(select n.nspname schema,t.typname name,jsonb_agg(e.enumlabel order by e.enumsortorder) labels from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum e on e.enumtypid=t.oid where n.nspname in('public','pos_private','inventory_private') group by n.nspname,t.typname)x)
) result; commit;
