import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function ShowcaseRequestsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: preference } = user ? await supabase.from("user_preferences").select("active_workspace_id").eq("user_id", user.id).maybeSingle() : { data: null };
  const workspaceId = preference?.active_workspace_id;
  const { data: requests } = workspaceId ? await supabase.from("showcase_requests").select("id,customer_name,status,subtotal,created_at,showcase_request_items(id,requested_quantity)").eq("workspace_id", workspaceId).order("created_at", { ascending: false }).limit(100) : { data: [] };
  return <main className="dashboard-responsive mx-auto max-w-[1200px] px-4 py-7 sm:px-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-td-accent-text">Showcase · Operations</p><h1 className="mt-3 text-3xl font-semibold text-td-primary">Customer requests</h1><p className="mt-2 text-sm text-td-muted">Review, pick, and complete customer requests without exposing internal inventory data.</p><div className="mt-7 overflow-hidden rounded-[24px] border border-td-ink/[.08] bg-td-surface/60"><div className="grid grid-cols-[1.3fr_.8fr_.7fr_.5fr] gap-4 border-b border-td-ink/[.08] px-5 py-3 text-xs font-bold uppercase tracking-[.12em] text-td-muted"><span>Customer</span><span>Status</span><span>Created</span><span>Total</span></div>{(requests ?? []).length ? (requests ?? []).map((row) => <Link key={row.id} href={`/dashboard/showcase/requests/${row.id}`} className="grid grid-cols-[1.3fr_.8fr_.7fr_.5fr] items-center gap-4 border-b border-td-ink/[.06] px-5 py-4 text-sm hover:bg-td-ink/[.025]"><span><strong className="block text-td-primary">{row.customer_name}</strong><small className="text-td-muted">{(row.showcase_request_items as Array<{ requested_quantity: number }> | null)?.reduce((sum, item) => sum + item.requested_quantity, 0) ?? 0} cards</small></span><span className="capitalize text-td-secondary">{row.status}</span><span className="text-td-muted">{new Date(row.created_at).toLocaleString()}</span><span className="font-semibold text-td-primary">${Number(row.subtotal).toFixed(2)}</span></Link>) : <div className="p-10 text-center text-sm text-td-muted">No customer requests yet.</div>}</div></main>;
}
