import type {
  DeckCard,
  DeckRecord,
  ManaColor,
} from "./types";

const makeCard = (
  id: string,
  name: string,
  manaValue: number,
  colors: ManaColor[],
  typeLine: string,
  category: string,
  price: number,
  owned = true,
  gameChanger = false,
  board: "commander" | "main" = "main",
): DeckCard => ({
  id,
  name,
  quantity: 1,
  manaValue,
  colors,
  typeLine,
  category,
  price,
  owned,
  gameChanger,
  board,
});

const atraxaCards: DeckCard[] = [
  makeCard("1", "Atraxa, Praetors' Voice", 4, ["W", "U", "B", "G"], "Legendary Creature", "Commander", 22.41, true, false, "commander"),
  makeCard("2", "Sol Ring", 1, ["C"], "Artifact", "Ramp", 1.42),
  makeCard("3", "Arcane Signet", 2, ["C"], "Artifact", "Ramp", 0.78),
  makeCard("4", "Swords to Plowshares", 1, ["W"], "Instant", "Removal", 1.15),
  makeCard("5", "Cyclonic Rift", 2, ["U"], "Instant", "Board Control", 32.77),
  makeCard("6", "Demonic Tutor", 2, ["B"], "Sorcery", "Tutor", 41.5, true, true),
  makeCard("7", "Doubling Season", 5, ["G"], "Enchantment", "Proliferate", 39.9),
  makeCard("8", "Teferi, Hero of Dominaria", 5, ["W", "U"], "Planeswalker", "Value", 8.21),
  makeCard("9", "Vorinclex, Monstrous Raider", 6, ["G"], "Legendary Creature", "Proliferate", 31.25),
  makeCard("10", "Farewell", 6, ["W"], "Sorcery", "Board Wipe", 2.88),
  makeCard("11", "The One Ring", 4, ["C"], "Legendary Artifact", "Card Draw", 79.14, true, true),
  makeCard("12", "Rhystic Study", 3, ["U"], "Enchantment", "Card Draw", 49.12),
  makeCard("13", "Smothering Tithe", 4, ["W"], "Enchantment", "Ramp", 28.44),
  makeCard("14", "Heroic Intervention", 2, ["G"], "Instant", "Protection", 9.82),
  makeCard("15", "Command Tower", 0, ["C"], "Land", "Land", 0.35),
  makeCard("16", "Breeding Pool", 0, ["U", "G"], "Land", "Land", 12.5),
  makeCard("17", "Godless Shrine", 0, ["W", "B"], "Land", "Land", 10.9, false),
  makeCard("18", "Watery Grave", 0, ["U", "B"], "Land", "Land", 11.4),
  makeCard("19", "Temple Garden", 0, ["W", "G"], "Land", "Land", 9.75),
  makeCard("20", "Polluted Delta", 0, ["U", "B"], "Land", "Land", 22.1, false),
];

export const decks: DeckRecord[] = [
  {
    id: "atraxa-superfriends",
    name: "Atraxa Superfriends",
    commander: "Atraxa, Praetors' Voice",
    format: "EDH",
    theme: "Planeswalkers & Proliferate",
    colors: ["W", "U", "B", "G"],
    marketValue: 842.16,
    ownedCount: 94,
    cardCount: 100,
    power: 7.1,
    updatedAt: "Today",
    status: "Building",
    cards: atraxaCards,
  },
  {
    id: "ur-dragon",
    name: "The Ur-Dragon",
    commander: "The Ur-Dragon",
    format: "EDH",
    theme: "Five-Color Dragon Tribal",
    colors: ["W", "U", "B", "R", "G"],
    marketValue: 1248.72,
    ownedCount: 100,
    cardCount: 100,
    power: 8.0,
    updatedAt: "Yesterday",
    status: "Complete",
    cards: atraxaCards,
  },
  {
    id: "krenko-mob-boss",
    name: "Krenko Mob Boss",
    commander: "Krenko, Mob Boss",
    format: "EDH",
    theme: "Goblin Tokens",
    colors: ["R"],
    marketValue: 286.45,
    ownedCount: 87,
    cardCount: 100,
    power: 6.3,
    updatedAt: "3 days ago",
    status: "Building",
    cards: atraxaCards,
  },
];

export const importExamples = [
  {
    source: "Moxfield",
    example: "1 Sol Ring\n1 Arcane Signet\n1 Command Tower",
  },
  {
    source: "ManaBox",
    example: "1x Sol Ring (CMM) 396\n1x Arcane Signet (ELD) 331",
  },
  {
    source: "MTGGoldfish",
    example: "1 Atraxa, Praetors' Voice\n1 Doubling Season",
  },
];
