import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { Tabs } from 'expo-router';
import { Platform, Pressable, StyleSheet, View } from 'react-native';
import { useAccount } from '@/providers/account';
import { color, elevation, radius } from '@/design';
const icons: Record<string,string>={index:'home',collection:'albums',scan:'scan','deal-desk':'calculator',sell:'pulse',profile:'person'};
export default function Layout(){const {accountType}=useAccount();const business=accountType==='seller'||accountType==='store';return <Tabs screenOptions={({route})=>({headerShown:false,tabBarShowLabel:true,tabBarActiveTintColor:color.primaryBright,tabBarInactiveTintColor:color.textMuted,tabBarStyle:s.tab,tabBarLabelStyle:s.label,tabBarIcon:({color:iconColor,size,focused})=>{const base=icons[route.name]??'ellipse';return route.name===(business?'deal-desk':'scan')?<View style={[s.center,focused&&s.centerActive]}><Ionicons name={base as any} color="#fff" size={25}/></View>:<Ionicons name={(focused?base:`${base}-outline`) as any} color={iconColor} size={size}/>},tabBarButton:(props)=><Pressable {...props as any} onPress={(event)=>{Haptics.selectionAsync();props.onPress?.(event as any)}}/>})}><Tabs.Screen name="index" options={{title:'Home'}}/><Tabs.Screen name="collection" options={{title:business?'Inventory':'Collection'}}/><Tabs.Screen name="scan" options={{title:'Scan',href:business?null:undefined}}/><Tabs.Screen name="deal-desk" options={{title:'Deal Desk',href:business?undefined:null}}/><Tabs.Screen name="sell" options={{title:'Signals'}}/><Tabs.Screen name="profile" options={{title:'Profile'}}/></Tabs>}
const s=StyleSheet.create({tab:{position:'absolute',left:14,right:14,bottom:Platform.OS==='ios'?18:10,height:Platform.OS==='ios'?76:68,paddingTop:8,paddingBottom:Platform.OS==='ios'?10:7,backgroundColor:'#0A1A2AF5',borderTopWidth:0,borderWidth:1,borderColor:color.border,borderRadius:26,...elevation.floating},label:{fontSize:10,fontWeight:'800'},center:{width:54,height:54,borderRadius:radius.lg,backgroundColor:color.primary,alignItems:'center',justifyContent:'center',marginTop:-22,borderWidth:4,borderColor:color.canvas,...elevation.floating},centerActive:{backgroundColor:color.primaryBright}});
