import type { ReactNode } from "react";

type ProductShellProps = { featureName: string; state: string };

const cards = [
  ["Pikachu ex", "Scarlet & Violet", "Recognized", "Shelf A · Bin 02", "yellow"],
  ["Charizard", "Obsidian Flames", "Recognized", "Shelf A · Bin 03", "red"],
  ["Mewtwo VSTAR", "Crown Zenith", "Needs review", "Review queue", "purple"],
  ["Umbreon VMAX", "Evolving Skies", "Recognized", "Shelf B · Bin 04"],
  ["Lugia V", "Silver Tempest", "Recognized", "Shelf B · Bin 04"],
  ["Gengar ex", "Phantom Forces", "Needs review", "Review queue"],
];

function TopBar({ featureName }: { featureName: string }) {
  return <header className="flex h-16 items-center justify-between border-b border-white/[.08] bg-[#101b2b] px-7 text-[#edf6ff]"><div className="flex items-center gap-9"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#35cafa] text-sm font-black text-[#071321]">TD</span><span className="text-sm font-semibold tracking-[.02em]">Trading Docks</span></div><span className="h-5 w-px bg-white/10" /><span className="text-sm text-[#9eb2cb]">{featureName}</span></div><div className="flex items-center gap-3 text-xs text-[#9eb2cb]"><span className="rounded-full border border-[#35cafa]/30 bg-[#35cafa]/10 px-3 py-1.5 text-[#6edbff]">Workspace</span><span className="grid h-8 w-8 place-items-center rounded-full bg-[#243653] font-semibold text-[#eaf4ff]">JS</span></div></header>;
}

function SideBar() {
  return <aside className="hidden w-52 shrink-0 border-r border-white/[.07] bg-[#0c1625] px-4 py-6 lg:block"><p className="px-3 text-[10px] font-bold uppercase tracking-[.2em] text-[#6d839f]">Operations</p><nav className="mt-4 space-y-1 text-sm"><NavItem active>Chaos Sort</NavItem><NavItem>Inventory</NavItem><NavItem>Locations</NavItem><NavItem>Batches</NavItem><NavItem>Marketplace</NavItem></nav><div className="mt-10 border-t border-white/[.07] pt-5"><p className="px-3 text-[10px] font-bold uppercase tracking-[.2em] text-[#6d839f]">Workspace</p><nav className="mt-3 space-y-1 text-sm"><NavItem>Activity</NavItem><NavItem>Settings</NavItem></nav></div></aside>;
}

function NavItem({ children, active }: { children: ReactNode; active?: boolean }) { return <div className={`rounded-lg px-3 py-2.5 ${active ? "bg-[#35cafa]/12 font-semibold text-[#6edbff]" : "text-[#9eb2cb]"}`}>{children}</div>; }

function StatusPill({ children, tone = "cyan" }: { children: ReactNode; tone?: "cyan" | "green" | "yellow" }) { const toneClass = tone === "green" ? "border-[#52d69a]/30 bg-[#52d69a]/10 text-[#71e4ac]" : tone === "yellow" ? "border-[#f4c95d]/30 bg-[#f4c95d]/10 text-[#f8d878]" : "border-[#35cafa]/30 bg-[#35cafa]/10 text-[#6edbff]"; return <span className={`rounded-full border px-2.5 py-1 text-[11px] font-semibold ${toneClass}`}>{children}</span>; }

function ProductHeader({ state }: { state: string }) { const label = state === "review" ? "Review queue" : state === "workflow" ? "Guided intake" : state === "inventory-result" ? "Inventory updated" : "Recognition session"; return <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#6d839f]">Chaos Sort</p><h1 className="mt-2 text-[30px] font-semibold tracking-[-.035em] text-[#edf6ff]">{label}</h1><p className="mt-2 text-sm text-[#9eb2cb]">Turn incoming cards into organized, searchable inventory.</p></div><div className="flex items-center gap-2"><StatusPill tone="green">Session active</StatusPill><button className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-[#b8c9dd]">More actions</button></div></div>; }

function ProgressBar({ state }: { state: string }) { const progress = state === "inventory-result" ? 100 : state === "review" ? 72 : state === "workflow" ? 46 : 75; return <div className="rounded-xl border border-white/[.08] bg-[#132239] p-4"><div className="flex items-center justify-between text-xs"><span className="font-semibold text-[#edf6ff]">Batch CS-2409 · 18 / 24 recognized</span><span className="text-[#6edbff]">{progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#263b59]"><div className="h-full rounded-full bg-[#35cafa]" style={{ width: `${progress}%` }} /></div><div className="mt-3 flex justify-between text-[11px] text-[#7f96b3]"><span>Scan</span><span>Identify</span><span>Confirm</span><span>Locate</span></div></div>; }

function CardThumbnail({ tone }: { tone?: string }) { const colors = tone === "red" ? "from-[#f07a66] via-[#f6b86a] to-[#5c2435]" : tone === "purple" ? "from-[#a68cff] via-[#433777] to-[#17152d]" : "from-[#f6d36b] via-[#64c5bd] to-[#233b70]"; return <div aria-hidden className={`h-16 w-12 shrink-0 rounded-md border border-white/20 bg-gradient-to-br ${colors} p-1 shadow-inner`}><div className="h-full rounded border border-white/30 bg-black/10" /></div>; }

function CardGrid({ state }: { state: string }) { const visible = state === "review" ? cards.slice(0, 6) : cards.slice(0, 5); return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(([name, set, status, location, tone]) => <article key={name} className="rounded-xl border border-white/[.08] bg-[#132239] p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><CardThumbnail tone={tone} /><div><p className="font-semibold text-[#edf6ff]">{name}</p><p className="mt-1 text-xs text-[#8fa6c1]">{set}</p></div></div><StatusPill tone={status === "Needs review" ? "yellow" : "green"}>{status}</StatusPill></div><div className="mt-5 flex items-center justify-between border-t border-white/[.07] pt-3 text-[11px]"><span className="text-[#7f96b3]">Position</span><span className="font-medium text-[#c5d5e7]">{state === "inventory-result" ? location : status === "Needs review" ? "Needs decision" : location}</span></div></article>)}</div>; }

function Workflow({ result = false }: { result?: boolean }) { const steps = result ? [["01", "Scan", "Complete"], ["02", "Identify", "Complete"], ["03", "Confirm", "Complete"], ["04", "Locate", "Complete"]] : [["01", "Scan", "Complete"], ["02", "Identify", "In progress"], ["03", "Confirm", "Next"], ["04", "Locate", "Queued"]]; return <div className="grid gap-3 sm:grid-cols-4">{steps.map(([number, title, status], index) => <div key={title} className={`rounded-xl border p-4 ${status === "In progress" ? "border-[#35cafa]/50 bg-[#35cafa]/10" : "border-white/[.08] bg-[#132239]"}`}><div className="flex items-center justify-between"><span className="text-xs font-semibold text-[#6edbff]">{number}</span><span className="text-[10px] uppercase tracking-[.12em] text-[#7f96b3]">{status}</span></div><p className="mt-6 font-semibold text-[#edf6ff]">{title}</p><p className="mt-1 text-xs text-[#8fa6c1]">{index === 0 ? "Capture card front" : index === 1 ? "Match against card library" : index === 2 ? "Confirm recognized item" : "Assign physical position"}</p></div>)}</div>; }

function CaptureContent({ state }: { state: string }) { if (state === "workflow") return <><ProgressBar state={state} /><section className="mt-5 rounded-xl border border-white/[.08] bg-[#101d30] p-5"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#6d839f]">Workflow</p><h2 className="mt-2 text-lg font-semibold text-[#edf6ff]">A clear path from scan to shelf</h2><p className="mt-1 text-sm text-[#9eb2cb]">Keep every recognition decision attached to the physical position it belongs to.</p><div className="mt-5"><Workflow /></div></section></>; if (state === "inventory-result") return <><div className="rounded-xl border border-[#52d69a]/30 bg-[#52d69a]/[.07] p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#52d69a] text-lg font-bold text-[#071321]">✓</span><div><h2 className="font-semibold text-[#edf6ff]">Inventory updated</h2><p className="mt-1 text-sm text-[#9eb2cb]">5 recognized cards are now searchable with their batch and physical positions.</p></div></div><div className="mt-5"><Workflow result /></div></div><div className="mt-5"><CardGrid state={state} /></div></>; return <><ProgressBar state={state} /><section className="mt-5"><div className="mb-3 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#6d839f]">Recognized cards</p><h2 className="mt-1 text-lg font-semibold text-[#edf6ff]">{state === "review" ? "Review before filing" : "Ready to confirm"}</h2></div><span className="text-xs text-[#8fa6c1]">{state === "review" ? "5 recognized · 1 needs review" : "5 of 6 cards recognized"}</span></div><CardGrid state={state} /></section></>; }

export function ProductCaptureShell({ featureName, state }: ProductShellProps) { const chaos = featureName.toLowerCase() === "chaos sort"; return <div data-marketing-capture-ready="true" data-marketing-product-capture="true" className="min-h-[900px] w-full min-w-[1100px] bg-[#0a101b] font-sans text-[#edf6ff]"><TopBar featureName={featureName} /><div className="flex min-h-[836px]"><SideBar /><div className="min-w-0 flex-1 px-10 py-8"><div className="mx-auto max-w-[1180px]"><ProductHeader state={chaos ? state : "primary"} />{chaos ? <div className="mt-8"><CaptureContent state={state} /></div> : <div className="mt-8 rounded-xl border border-white/[.08] bg-[#132239] p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#6d839f]">{featureName}</p><h2 className="mt-3 text-2xl font-semibold">A clearer operating workflow</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#9eb2cb]">See the approved workflow in context, with the next action and its operational outcome in the same view.</p><div className="mt-8"><Workflow /></div></div>}</div></div></div></div>; }

export const MarketingProductShell = ProductCaptureShell;
