import {
  Activity,
  BarChart3,
  BellRing,
  CalendarDays,
  LibraryBig,
  Bot,
  Boxes,
  BrainCircuit,
  CircleDollarSign,
  Flame,
  Gauge,
  Heart,
  ListChecks,
  PackageCheck,
  ScanLine,
  ShoppingBag,
  Store,
  Tags,
  TrendingUp,
} from "lucide-react";

import type {
  AccountPlan,
  DashboardLayoutId,
  DashboardWidget,
  WidgetDefinition,
} from "./types";

export const PLAN_RANK: Record<AccountPlan, number> = {
  starter: 0,
  pro: 1,
  business: 2,
};

export const WIDGETS: WidgetDefinition[] = [
  {
    id: "inventory-value",
    title: "Inventory Value",
    description: "Current portfolio value and daily movement.",
    module: "Inventory",
    minimumPlan: "starter",
    defaultSize: "small",
    icon: CircleDollarSign,
  },
  {
    id: "inventory-count",
    title: "Inventory",
    description: "Total cards with intake and listing context.",
    module: "Inventory",
    minimumPlan: "starter",
    defaultSize: "small",
    icon: Boxes,
  },
  {
    id: "collection-growth",
    title: "Collection Growth",
    description: "Monthly portfolio growth across the current year.",
    module: "Collection",
    minimumPlan: "starter",
    defaultSize: "medium",
    icon: TrendingUp,
  },
  {
    id: "recently-added",
    title: "Recently Added",
    description: "The newest cards and products in your workspace.",
    module: "Collection",
    minimumPlan: "starter",
    defaultSize: "medium",
    icon: PackageCheck,
  },
  {
    id: "binder-usage",
    title: "Binder Usage",
    description: "Capacity and organization health by binder.",
    module: "Organization",
    minimumPlan: "starter",
    defaultSize: "medium",
    icon: LibraryBig,
  },
  {
    id: "chaos-sort",
    title: "Chaos Sort Queue",
    description: "Unsorted intake waiting to be processed.",
    module: "Scanning",
    minimumPlan: "starter",
    defaultSize: "medium",
    icon: ScanLine,
  },
  {
    id: "wishlist",
    title: "Wishlist",
    description: "Wanted cards and target acquisition prices.",
    module: "Collection",
    minimumPlan: "starter",
    defaultSize: "medium",
    icon: Heart,
  },
  {
    id: "commander-staples",
    title: "Commander Staples",
    description: "High-demand cards detected in your collection.",
    module: "Collection",
    minimumPlan: "starter",
    defaultSize: "medium",
    icon: Flame,
  },
  {
    id: "revenue",
    title: "Revenue",
    description: "Revenue, growth, and average daily sales.",
    module: "Finance",
    minimumPlan: "pro",
    defaultSize: "small",
    icon: CircleDollarSign,
  },
  {
    id: "profit",
    title: "Profit",
    description: "Net profit after costs and marketplace fees.",
    module: "Finance",
    minimumPlan: "pro",
    defaultSize: "small",
    icon: Gauge,
  },
  {
    id: "orders",
    title: "Orders",
    description: "Open orders, fulfillment status, and alerts.",
    module: "Orders",
    minimumPlan: "pro",
    defaultSize: "medium",
    icon: ShoppingBag,
  },
  {
    id: "listing-queue",
    title: "Listing Queue",
    description: "Cards ready to list across connected channels.",
    module: "Marketplaces",
    minimumPlan: "pro",
    defaultSize: "medium",
    icon: ListChecks,
  },
  {
    id: "marketplace-health",
    title: "Marketplace Health",
    description: "Sync status for TCGplayer, eBay, and Mana Pool.",
    module: "Marketplaces",
    minimumPlan: "pro",
    defaultSize: "medium",
    icon: Store,
  },
  {
    id: "price-alerts",
    title: "Price Alerts",
    description: "Meaningful market movement requiring attention.",
    module: "Analytics",
    minimumPlan: "pro",
    defaultSize: "medium",
    icon: BellRing,
  },
  {
    id: "inventory-heatmap",
    title: "Inventory Heat Map",
    description: "Inventory concentration by set and category.",
    module: "Analytics",
    minimumPlan: "pro",
    defaultSize: "large",
    icon: BarChart3,
  },
  {
    id: "automation-queue",
    title: "Automation Queue",
    description: "Running and scheduled workflow activity.",
    module: "Automation",
    minimumPlan: "pro",
    defaultSize: "medium",
    icon: Bot,
  },
  {
    id: "tasks",
    title: "Tasks",
    description: "Operational tasks requiring attention.",
    module: "Operations",
    minimumPlan: "pro",
    defaultSize: "medium",
    icon: Tags,
  },
  {
    id: "business-calendar",
    title: "Business Calendar",
    description: "Schedule supply orders, events, staffing, tournaments, and operational deadlines.",
    module: "Operations",
    minimumPlan: "starter",
    defaultSize: "large",
    icon: CalendarDays,
  },
  {
    id: "ai-insights",
    title: "AI Assistant",
    description: "Recommendations generated from your workspace.",
    module: "AI",
    minimumPlan: "business",
    defaultSize: "large",
    icon: BrainCircuit,
  },
  {
    id: "team-activity",
    title: "Team Activity",
    description: "Recent actions from employees and administrators.",
    module: "Team",
    minimumPlan: "business",
    defaultSize: "medium",
    icon: Activity,
  },
];

export const DEFAULT_LAYOUTS: Record<DashboardLayoutId, DashboardWidget[]> = {
  home: [
    { id: "inventory-value", size: "small" },
    { id: "inventory-count", size: "small" },
    { id: "revenue", size: "small" },
    { id: "orders", size: "small" },
    { id: "collection-growth", size: "medium" },
    { id: "business-calendar", size: "large" },
    { id: "marketplace-health", size: "medium" },
    { id: "automation-queue", size: "medium" },
    { id: "ai-insights", size: "large" },
  ],
  business: [
    { id: "revenue", size: "small" },
    { id: "profit", size: "small" },
    { id: "orders", size: "medium" },
    { id: "listing-queue", size: "medium" },
    { id: "marketplace-health", size: "medium" },
    { id: "business-calendar", size: "large" },
    { id: "price-alerts", size: "medium" },
    { id: "ai-insights", size: "large" },
  ],
  inventory: [
    { id: "inventory-value", size: "small" },
    { id: "inventory-count", size: "small" },
    { id: "chaos-sort", size: "medium" },
    { id: "binder-usage", size: "medium" },
    { id: "recently-added", size: "medium" },
    { id: "inventory-heatmap", size: "large" },
  ],
  analytics: [
    { id: "revenue", size: "small" },
    { id: "profit", size: "small" },
    { id: "collection-growth", size: "medium" },
    { id: "inventory-heatmap", size: "large" },
    { id: "price-alerts", size: "medium" },
  ],
  automation: [
    { id: "automation-queue", size: "large" },
    { id: "business-calendar", size: "large" },
    { id: "tasks", size: "medium" },
    { id: "ai-insights", size: "large" },
    { id: "team-activity", size: "medium" },
  ],
};

export function canUseWidget(
  widget: WidgetDefinition,
  plan: AccountPlan,
): boolean {
  return PLAN_RANK[plan] >= PLAN_RANK[widget.minimumPlan];
}

