import type { LucideIcon } from "lucide-react";
import {
  Archive,
  Bot,
  Boxes,
  Camera,
  CircleDollarSign,
  ClipboardList,
  FileSpreadsheet,
  FolderPlus,
  Package,
  RefreshCw,
  ScanLine,
  ShoppingBag,
  Sparkles,
  Tags,
  Trophy,
  Warehouse,
  Zap,
} from "lucide-react";

export type QuickCreateGroup =
  | "Inventory"
  | "Organization"
  | "Imports"
  | "Commerce"
  | "Automation";

export type QuickCreateItem = {
  id: string;
  title: string;
  description: string;
  href: string;
  group: QuickCreateGroup;
  icon: LucideIcon;
  keywords: string[];
  shortcut?: string;
  workspaceTypes?: Array<
    "Collector" | "Seller" | "LGS" | "Warehouse"
  >;
};

export const quickCreateItems: QuickCreateItem[] = [
  {
    id: "add-single",
    title: "Add Single Card",
    description: "Create a new single-card inventory record.",
    href: "/dashboard/inventory/new?type=single",
    group: "Inventory",
    icon: Sparkles,
    keywords: [
      "single",
      "card",
      "mtg",
      "pokemon",
      "inventory",
      "add",
    ],
    shortcut: "S",
  },
  {
    id: "add-sealed",
    title: "Add Sealed Product",
    description: "Add a booster box, bundle, pack, or deck.",
    href: "/dashboard/inventory/new?type=sealed",
    group: "Inventory",
    icon: Package,
    keywords: [
      "sealed",
      "booster",
      "box",
      "bundle",
      "pack",
      "deck",
    ],
  },
  {
    id: "add-graded",
    title: "Add Graded Card",
    description: "Record a PSA, BGS, CGC, or SGC slab.",
    href: "/dashboard/inventory/new?type=graded",
    group: "Inventory",
    icon: Trophy,
    keywords: [
      "graded",
      "grade",
      "psa",
      "bgs",
      "cgc",
      "sgc",
      "slab",
    ],
  },
  {
    id: "add-bulk",
    title: "Add Bulk Inventory",
    description: "Create a bulk lot, row, or storage batch.",
    href: "/dashboard/inventory/new?type=bulk",
    group: "Inventory",
    icon: Boxes,
    keywords: [
      "bulk",
      "lot",
      "commons",
      "uncommons",
      "box",
      "inventory",
    ],
  },
  {
    id: "create-binder",
    title: "Create Binder",
    description: "Create a binder and configure its layout.",
    href: "/dashboard/organization/binders/new",
    group: "Organization",
    icon: FolderPlus,
    keywords: [
      "binder",
      "collection",
      "pages",
      "organization",
      "folder",
    ],
    shortcut: "B",
  },
  {
    id: "create-storage",
    title: "Create Storage Location",
    description: "Add a box, shelf, bin, vault, or warehouse area.",
    href: "/dashboard/organization/locations/new",
    group: "Organization",
    icon: Warehouse,
    keywords: [
      "storage",
      "location",
      "shelf",
      "bin",
      "box",
      "warehouse",
      "vault",
    ],
  },
  {
    id: "create-tag",
    title: "Create Inventory Tag",
    description: "Create a reusable tag for inventory organization.",
    href: "/dashboard/organization/tags/new",
    group: "Organization",
    icon: Tags,
    keywords: [
      "tag",
      "label",
      "category",
      "organization",
      "inventory",
    ],
  },
  {
    id: "import-csv",
    title: "Import CSV",
    description: "Upload inventory from a spreadsheet or export.",
    href: "/dashboard/imports/csv",
    group: "Imports",
    icon: FileSpreadsheet,
    keywords: [
      "csv",
      "spreadsheet",
      "excel",
      "import",
      "upload",
      "file",
    ],
    shortcut: "I",
  },
  {
    id: "import-scanner",
    title: "Import Scanner Session",
    description: "Import cards captured through your scanner workflow.",
    href: "/dashboard/imports/scanner",
    group: "Imports",
    icon: ScanLine,
    keywords: [
      "scanner",
      "scan",
      "camera",
      "cards",
      "import",
      "session",
    ],
  },
  {
    id: "capture-card",
    title: "Capture Card Image",
    description: "Use an image to identify and add a card.",
    href: "/dashboard/imports/capture",
    group: "Imports",
    icon: Camera,
    keywords: [
      "camera",
      "photo",
      "image",
      "capture",
      "recognition",
      "scan",
    ],
  },
  {
    id: "marketplace-import",
    title: "Import Marketplace Inventory",
    description: "Import products from a connected marketplace.",
    href: "/dashboard/imports/marketplace",
    group: "Imports",
    icon: RefreshCw,
    keywords: [
      "marketplace",
      "tcgplayer",
      "ebay",
      "shopify",
      "mana pool",
      "import",
      "sync",
    ],
    workspaceTypes: ["Seller", "LGS", "Warehouse"],
  },
  {
    id: "create-listing",
    title: "Create Marketplace Listing",
    description: "Publish an inventory item to a sales channel.",
    href: "/dashboard/marketplaces/listings/new",
    group: "Commerce",
    icon: ShoppingBag,
    keywords: [
      "listing",
      "marketplace",
      "sell",
      "tcgplayer",
      "ebay",
      "shopify",
    ],
    shortcut: "L",
    workspaceTypes: ["Seller", "LGS"],
  },
  {
    id: "manual-sale",
    title: "Record Manual Sale",
    description: "Create an in-person or off-platform transaction.",
    href: "/dashboard/orders/new?type=manual",
    group: "Commerce",
    icon: CircleDollarSign,
    keywords: [
      "sale",
      "manual",
      "transaction",
      "cash",
      "order",
      "sold",
    ],
    workspaceTypes: ["Seller", "LGS"],
  },
  {
    id: "purchase-order",
    title: "Create Purchase Order",
    description: "Record incoming inventory from a supplier.",
    href: "/dashboard/purchases/new",
    group: "Commerce",
    icon: ClipboardList,
    keywords: [
      "purchase",
      "order",
      "supplier",
      "vendor",
      "incoming",
      "stock",
    ],
    workspaceTypes: ["LGS", "Warehouse"],
  },
  {
    id: "inventory-transfer",
    title: "Create Inventory Transfer",
    description: "Move inventory between locations or workspaces.",
    href: "/dashboard/inventory/transfers/new",
    group: "Commerce",
    icon: Archive,
    keywords: [
      "transfer",
      "move",
      "inventory",
      "location",
      "warehouse",
      "workspace",
    ],
    workspaceTypes: ["Seller", "LGS", "Warehouse"],
  },
  {
    id: "new-automation",
    title: "Create Automation",
    description: "Create a rule for repetitive inventory tasks.",
    href: "/dashboard/automation/new",
    group: "Automation",
    icon: Bot,
    keywords: [
      "automation",
      "rule",
      "workflow",
      "bot",
      "automatic",
      "trigger",
    ],
    shortcut: "A",
  },
  {
    id: "bulk-price-update",
    title: "Create Bulk Price Update",
    description: "Update prices using configurable pricing rules.",
    href: "/dashboard/automation/pricing/new",
    group: "Automation",
    icon: Zap,
    keywords: [
      "bulk",
      "price",
      "pricing",
      "update",
      "repricer",
      "automation",
    ],
    workspaceTypes: ["Seller", "LGS"],
  },
];