export const PREBUILT_SCANBOT_ACCEPTED_SIZE_SCORE = 45;
export const PREBUILT_SCANBOT_ACCEPTED_ANGLE_SCORE = 55;
export const PREBUILT_SCANBOT_AUTO_SNAPPING_ENABLED = true;
export const PREBUILT_SCANBOT_AUTO_SNAPPING_SENSITIVITY = 1.0;
export const PREBUILT_SCANBOT_AUTO_SNAPPING_DELAY_SECONDS = 0.1;
export const PREBUILT_SCANBOT_PHOTO_QUALITY_PRIORITIZATION = 'BALANCED' as const;
