// Generated by scripts/verify-demo-market-artwork.mjs. Do not hand-edit image URLs.
export const VERIFIED_DEMO_ARTWORK = [
  {
    "game": "magic",
    "provider": "scryfall",
    "providerId": "66024e69-ad60-4c9a-a0ca-da138d33ad80",
    "name": "Mox Amber",
    "setCode": "dom",
    "setName": "Dominaria",
    "collectorNumber": "224",
    "language": "English",
    "imageUrl": "https://cards.scryfall.io/normal/front/6/6/66024e69-ad60-4c9a-a0ca-da138d33ad80.jpg?1783934955",
    "thumbnailUrl": "https://cards.scryfall.io/small/front/6/6/66024e69-ad60-4c9a-a0ca-da138d33ad80.jpg?1783934955",
    "providerCardUrl": "https://scryfall.com/card/dom/224/mox-amber?utm_source=api",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:32.070Z",
      "images": [
        {
          "url": "https://cards.scryfall.io/normal/front/6/6/66024e69-ad60-4c9a-a0ca-da138d33ad80.jpg?1783934955",
          "width": 488,
          "height": 680,
          "contentType": "image/jpeg",
          "sha256": "385472fdaf89841e4521f15001145fc81b0a804820bdeb1019d7425fd20dd72c"
        },
        {
          "url": "https://cards.scryfall.io/small/front/6/6/66024e69-ad60-4c9a-a0ca-da138d33ad80.jpg?1783934955",
          "width": 146,
          "height": 204,
          "contentType": "image/jpeg",
          "sha256": "d98a3254c1211261a1b57816efeb2a957f556b28f2883014b6b3b792e99fb50e"
        }
      ]
    }
  },
  {
    "game": "magic",
    "provider": "scryfall",
    "providerId": "b61634ae-05be-4b56-8ebb-9d4ade902e42",
    "name": "Lightning Greaves",
    "setCode": "msc",
    "setName": "Marvel Super Heroes Commander",
    "collectorNumber": "202",
    "language": "English",
    "imageUrl": "https://cards.scryfall.io/normal/front/b/6/b61634ae-05be-4b56-8ebb-9d4ade902e42.jpg?1783903217",
    "thumbnailUrl": "https://cards.scryfall.io/small/front/b/6/b61634ae-05be-4b56-8ebb-9d4ade902e42.jpg?1783903217",
    "providerCardUrl": "https://scryfall.com/card/msc/202/lightning-greaves?utm_source=api",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:32.176Z",
      "images": [
        {
          "url": "https://cards.scryfall.io/normal/front/b/6/b61634ae-05be-4b56-8ebb-9d4ade902e42.jpg?1783903217",
          "width": 488,
          "height": 680,
          "contentType": "image/jpeg",
          "sha256": "4ea7c794477637bc90ba6cbda85bdb00964f856e7da9d22bfb62e36f8dbd6240"
        },
        {
          "url": "https://cards.scryfall.io/small/front/b/6/b61634ae-05be-4b56-8ebb-9d4ade902e42.jpg?1783903217",
          "width": 146,
          "height": 204,
          "contentType": "image/jpeg",
          "sha256": "dfdf20eb45a9ea2fc1665dd763114e844ac89994b98987ca469d5a0df916eb2b"
        }
      ]
    }
  },
  {
    "game": "magic",
    "provider": "scryfall",
    "providerId": "d5806e68-1054-458e-866d-1f2470f682b2",
    "name": "The One Ring",
    "setCode": "ltr",
    "setName": "The Lord of the Rings: Tales of Middle-earth",
    "collectorNumber": "246",
    "language": "English",
    "imageUrl": "https://cards.scryfall.io/normal/front/d/5/d5806e68-1054-458e-866d-1f2470f682b2.jpg?1783916239",
    "thumbnailUrl": "https://cards.scryfall.io/small/front/d/5/d5806e68-1054-458e-866d-1f2470f682b2.jpg?1783916239",
    "providerCardUrl": "https://scryfall.com/card/ltr/246/the-one-ring?utm_source=api",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:32.268Z",
      "images": [
        {
          "url": "https://cards.scryfall.io/normal/front/d/5/d5806e68-1054-458e-866d-1f2470f682b2.jpg?1783916239",
          "width": 488,
          "height": 680,
          "contentType": "image/jpeg",
          "sha256": "5e37cc43755aecab1c45f2137df9ebf91721b0202370b09ba58fd1638226181e"
        },
        {
          "url": "https://cards.scryfall.io/small/front/d/5/d5806e68-1054-458e-866d-1f2470f682b2.jpg?1783916239",
          "width": 146,
          "height": 204,
          "contentType": "image/jpeg",
          "sha256": "ecdb02fe37085ccc13c29cedae9e2e32651d96c5bdc1e9a844e80945c72bc95d"
        }
      ]
    }
  },
  {
    "game": "magic",
    "provider": "scryfall",
    "providerId": "9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b",
    "name": "Rhystic Study",
    "setCode": "j22",
    "setName": "Jumpstart 2022",
    "collectorNumber": "114",
    "language": "English",
    "imageUrl": "https://cards.scryfall.io/normal/front/9/f/9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b.jpg?1783919146",
    "thumbnailUrl": "https://cards.scryfall.io/small/front/9/f/9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b.jpg?1783919146",
    "providerCardUrl": "https://scryfall.com/card/j22/114/rhystic-study?utm_source=api",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:32.361Z",
      "images": [
        {
          "url": "https://cards.scryfall.io/normal/front/9/f/9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b.jpg?1783919146",
          "width": 488,
          "height": 680,
          "contentType": "image/jpeg",
          "sha256": "4fa6956d9fc0e759da92a18bd132eaa17321df650f22bbd64156ceb890197766"
        },
        {
          "url": "https://cards.scryfall.io/small/front/9/f/9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b.jpg?1783919146",
          "width": 146,
          "height": 204,
          "contentType": "image/jpeg",
          "sha256": "cca3d16db6dc6dce1e5ad2fb0a873f881bfdf306cac1025e15b33302705ec0ef"
        }
      ]
    }
  },
  {
    "game": "magic",
    "provider": "scryfall",
    "providerId": "3aad15a2-8a1b-4460-9b06-e85863081878",
    "name": "Cavern of Souls",
    "setCode": "lci",
    "setName": "The Lost Caverns of Ixalan",
    "collectorNumber": "269",
    "language": "English",
    "imageUrl": "https://cards.scryfall.io/normal/front/3/a/3aad15a2-8a1b-4460-9b06-e85863081878.jpg?1783913719",
    "thumbnailUrl": "https://cards.scryfall.io/small/front/3/a/3aad15a2-8a1b-4460-9b06-e85863081878.jpg?1783913719",
    "providerCardUrl": "https://scryfall.com/card/lci/269/cavern-of-souls?utm_source=api",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:32.487Z",
      "images": [
        {
          "url": "https://cards.scryfall.io/normal/front/3/a/3aad15a2-8a1b-4460-9b06-e85863081878.jpg?1783913719",
          "width": 488,
          "height": 680,
          "contentType": "image/jpeg",
          "sha256": "49bae1fd3548a8bb9d2f621d8ed34b929efc65f80cbea72b70281a15cc16f82b"
        },
        {
          "url": "https://cards.scryfall.io/small/front/3/a/3aad15a2-8a1b-4460-9b06-e85863081878.jpg?1783913719",
          "width": 146,
          "height": 204,
          "contentType": "image/jpeg",
          "sha256": "517d65466ab6f779c2fb80eb71dd8d2641ac6f07ea28c0ca3391e0d56cff1884"
        }
      ]
    }
  },
  {
    "game": "pokemon",
    "provider": "pokemon-tcg-api",
    "providerId": "sv8-238",
    "name": "Pikachu ex",
    "setCode": "sv8",
    "setName": "Surging Sparks",
    "collectorNumber": "238",
    "language": "English",
    "imageUrl": "https://images.pokemontcg.io/sv8/238_hires.png",
    "thumbnailUrl": "https://images.pokemontcg.io/sv8/238.png",
    "providerCardUrl": "https://api.pokemontcg.io/v2/cards/sv8-238",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:32.684Z",
      "images": [
        {
          "url": "https://images.pokemontcg.io/sv8/238_hires.png",
          "width": 733,
          "height": 1024,
          "contentType": "image/png",
          "sha256": "5d083fb8217ce0567298511908e2a5f4872f1d5f4c40bba55d717f6ccbb0facd"
        },
        {
          "url": "https://images.pokemontcg.io/sv8/238.png",
          "width": 245,
          "height": 342,
          "contentType": "image/png",
          "sha256": "37bb8733de3e362fd54e5e90a90eb6026a3f3aa376d952ab54a3e95ede62c852"
        }
      ]
    }
  },
  {
    "game": "pokemon",
    "provider": "pokemon-tcg-api",
    "providerId": "sv3pt5-199",
    "name": "Charizard ex",
    "setCode": "sv3pt5",
    "setName": "151",
    "collectorNumber": "199",
    "language": "English",
    "imageUrl": "https://images.pokemontcg.io/sv3pt5/199_hires.png",
    "thumbnailUrl": "https://images.pokemontcg.io/sv3pt5/199.png",
    "providerCardUrl": "https://api.pokemontcg.io/v2/cards/sv3pt5-199",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:32.809Z",
      "images": [
        {
          "url": "https://images.pokemontcg.io/sv3pt5/199_hires.png",
          "width": 733,
          "height": 1024,
          "contentType": "image/png",
          "sha256": "0110f9df7555bc0868af581077db31176f26c890ec3d4a9c3fb95fba66f60a3a"
        },
        {
          "url": "https://images.pokemontcg.io/sv3pt5/199.png",
          "width": 245,
          "height": 342,
          "contentType": "image/png",
          "sha256": "ecd06ba1afa81077e4cf37a4c14446b985ce580e6f2e63139e5ae63977985c15"
        }
      ]
    }
  },
  {
    "game": "pokemon",
    "provider": "pokemon-tcg-api",
    "providerId": "sv3pt5-205",
    "name": "Mew ex",
    "setCode": "sv3pt5",
    "setName": "151",
    "collectorNumber": "205",
    "language": "English",
    "imageUrl": "https://images.pokemontcg.io/sv3pt5/205_hires.png",
    "thumbnailUrl": "https://images.pokemontcg.io/sv3pt5/205.png",
    "providerCardUrl": "https://api.pokemontcg.io/v2/cards/sv3pt5-205",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:32.921Z",
      "images": [
        {
          "url": "https://images.pokemontcg.io/sv3pt5/205_hires.png",
          "width": 733,
          "height": 1024,
          "contentType": "image/png",
          "sha256": "f19e1451771a9a8f7e6a412d28ab316233fb8f7822267c259aeb658a84c8fb1e"
        },
        {
          "url": "https://images.pokemontcg.io/sv3pt5/205.png",
          "width": 245,
          "height": 342,
          "contentType": "image/png",
          "sha256": "ef69e0dfe1dae585ba10d52be097ff20f68aaf0f6eb365bf7254af9c8255c763"
        }
      ]
    }
  },
  {
    "game": "pokemon-japan",
    "provider": "tcgdex",
    "providerId": "SV2a-025",
    "name": "ピカチュウ",
    "setCode": "SV2a",
    "setName": "ポケモンカード151",
    "collectorNumber": "025",
    "language": "Japanese",
    "imageUrl": "https://assets.tcgdex.net/ja/SV/SV2a/025/high.webp",
    "thumbnailUrl": "https://assets.tcgdex.net/ja/SV/SV2a/025/low.webp",
    "providerCardUrl": "https://api.tcgdex.net/v2/ja/cards/SV2a-025",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:33.421Z",
      "images": [
        {
          "url": "https://assets.tcgdex.net/ja/SV/SV2a/025/high.webp",
          "width": 600,
          "height": 825,
          "contentType": "image/webp",
          "sha256": "d62f7423c8d352e5d37a2cd81311eb027994c67fec0cceaeec89a53e35f51624"
        },
        {
          "url": "https://assets.tcgdex.net/ja/SV/SV2a/025/low.webp",
          "width": 245,
          "height": 337,
          "contentType": "image/webp",
          "sha256": "bcd7844c05e13fda50856c97e771e0d7fc22b99213359bf3a3abb2889205d4b0"
        }
      ]
    }
  },
  {
    "game": "pokemon-japan",
    "provider": "tcgdex",
    "providerId": "SV2a-006",
    "name": "リザードンex",
    "setCode": "SV2a",
    "setName": "ポケモンカード151",
    "collectorNumber": "006",
    "language": "Japanese",
    "imageUrl": "https://assets.tcgdex.net/ja/SV/SV2a/006/high.webp",
    "thumbnailUrl": "https://assets.tcgdex.net/ja/SV/SV2a/006/low.webp",
    "providerCardUrl": "https://api.tcgdex.net/v2/ja/cards/SV2a-006",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:33.652Z",
      "images": [
        {
          "url": "https://assets.tcgdex.net/ja/SV/SV2a/006/high.webp",
          "width": 600,
          "height": 825,
          "contentType": "image/webp",
          "sha256": "e31f4993373d4a5eb75a37bea4ac3c25a5bedb4b97b63f25c7a18bc9f43a3c5c"
        },
        {
          "url": "https://assets.tcgdex.net/ja/SV/SV2a/006/low.webp",
          "width": 245,
          "height": 337,
          "contentType": "image/webp",
          "sha256": "f2b6c35bf1afb47011ab2ecb181c03feb26dbc1ecc0b0a15f9e6fddc4810841c"
        }
      ]
    }
  },
  {
    "game": "pokemon-japan",
    "provider": "tcgdex",
    "providerId": "SV2a-151",
    "name": "ミュウex",
    "setCode": "SV2a",
    "setName": "ポケモンカード151",
    "collectorNumber": "151",
    "language": "Japanese",
    "imageUrl": "https://assets.tcgdex.net/ja/SV/SV2a/151/high.webp",
    "thumbnailUrl": "https://assets.tcgdex.net/ja/SV/SV2a/151/low.webp",
    "providerCardUrl": "https://api.tcgdex.net/v2/ja/cards/SV2a-151",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:33.834Z",
      "images": [
        {
          "url": "https://assets.tcgdex.net/ja/SV/SV2a/151/high.webp",
          "width": 600,
          "height": 825,
          "contentType": "image/webp",
          "sha256": "7720b1ada5c9564c2cd7f0972b11f15e3e640bf5ad9e7a7f043672cd84291a32"
        },
        {
          "url": "https://assets.tcgdex.net/ja/SV/SV2a/151/low.webp",
          "width": 245,
          "height": 337,
          "contentType": "image/webp",
          "sha256": "8c1e273ebb4e92b63a18d4779cc6a0243125d94d082025529d8f87069eb2458a"
        }
      ]
    }
  },
  {
    "game": "lorcana",
    "provider": "lorcast",
    "providerId": "crd_04bca46a8e2d4e9ba0fbdbfc6c99e51e",
    "name": "Elsa — Spirit of Winter",
    "setCode": "1",
    "setName": "The First Chapter",
    "collectorNumber": "42",
    "language": "English",
    "imageUrl": "https://cards.lorcast.io/card/digital/large/crd_04bca46a8e2d4e9ba0fbdbfc6c99e51e.avif?1709690747",
    "thumbnailUrl": "https://cards.lorcast.io/card/digital/small/crd_04bca46a8e2d4e9ba0fbdbfc6c99e51e.avif?1709690747",
    "providerCardUrl": "https://api.lorcast.com/v0/cards/1/42",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:34.074Z",
      "images": [
        {
          "url": "https://cards.lorcast.io/card/digital/large/crd_04bca46a8e2d4e9ba0fbdbfc6c99e51e.avif?1709690747",
          "width": 674,
          "height": 940,
          "contentType": "image/avif",
          "sha256": "442eaf806fb6a2a30422f1ee262663e5137927cc964ddec3e29dec830ef2c93b"
        },
        {
          "url": "https://cards.lorcast.io/card/digital/small/crd_04bca46a8e2d4e9ba0fbdbfc6c99e51e.avif?1709690747",
          "width": 146,
          "height": 204,
          "contentType": "image/avif",
          "sha256": "eb0b44974792fb15f7d7f9a103b6f1dade7a45ce4e0cb0af5e4ecc81af8c8d4b"
        }
      ]
    }
  },
  {
    "game": "lorcana",
    "provider": "lorcast",
    "providerId": "crd_c32945ecfd3d44859d3af3841977a737",
    "name": "Stitch — Rock Star",
    "setCode": "1",
    "setName": "The First Chapter",
    "collectorNumber": "23",
    "language": "English",
    "imageUrl": "https://cards.lorcast.io/card/digital/large/crd_c32945ecfd3d44859d3af3841977a737.avif?1709690747",
    "thumbnailUrl": "https://cards.lorcast.io/card/digital/small/crd_c32945ecfd3d44859d3af3841977a737.avif?1709690747",
    "providerCardUrl": "https://api.lorcast.com/v0/cards/1/23",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:34.343Z",
      "images": [
        {
          "url": "https://cards.lorcast.io/card/digital/large/crd_c32945ecfd3d44859d3af3841977a737.avif?1709690747",
          "width": 674,
          "height": 940,
          "contentType": "image/avif",
          "sha256": "89c9a1f1a592b59b16ab1b92481648bf40d589fa9d7cc280c3a342c7ca727fa0"
        },
        {
          "url": "https://cards.lorcast.io/card/digital/small/crd_c32945ecfd3d44859d3af3841977a737.avif?1709690747",
          "width": 146,
          "height": 204,
          "contentType": "image/avif",
          "sha256": "91fca93d0f2b66b830e7d529dd397d16fe932f241fc4546a54556b50455da3d2"
        }
      ]
    }
  },
  {
    "game": "lorcana",
    "provider": "lorcast",
    "providerId": "crd_e74ef94562b9440e8dd95ada098728d6",
    "name": "Mickey Mouse — Brave Little Tailor",
    "setCode": "1",
    "setName": "The First Chapter",
    "collectorNumber": "115",
    "language": "English",
    "imageUrl": "https://cards.lorcast.io/card/digital/large/crd_e74ef94562b9440e8dd95ada098728d6.avif?1709690747",
    "thumbnailUrl": "https://cards.lorcast.io/card/digital/small/crd_e74ef94562b9440e8dd95ada098728d6.avif?1709690747",
    "providerCardUrl": "https://api.lorcast.com/v0/cards/1/115",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:34.574Z",
      "images": [
        {
          "url": "https://cards.lorcast.io/card/digital/large/crd_e74ef94562b9440e8dd95ada098728d6.avif?1709690747",
          "width": 674,
          "height": 940,
          "contentType": "image/avif",
          "sha256": "ee04b6501be94ef6824f9fb29a71a4cae139e46c8737117122d4f8e58c2de96f"
        },
        {
          "url": "https://cards.lorcast.io/card/digital/small/crd_e74ef94562b9440e8dd95ada098728d6.avif?1709690747",
          "width": 146,
          "height": 204,
          "contentType": "image/avif",
          "sha256": "130c5e7ec9b66f0369c7b351e9213f5c53b967a016459f9a135fca735d02b325"
        }
      ]
    }
  },
  {
    "game": "one-piece",
    "provider": "optcg-api",
    "providerId": "OP01-003",
    "name": "Monkey.D.Luffy (003)",
    "setCode": "OP-01",
    "setName": "Romance Dawn",
    "collectorNumber": "OP01-003",
    "language": "English",
    "imageUrl": "https://optcgapi.com/media/static/Card_Images/OP01-003.jpg",
    "thumbnailUrl": "https://optcgapi.com/media/static/Card_Images/OP01-003.jpg",
    "providerCardUrl": "https://optcgapi.com/api/sets/card/OP01-003/",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:34.862Z",
      "images": [
        {
          "url": "https://optcgapi.com/media/static/Card_Images/OP01-003.jpg",
          "width": 600,
          "height": 838,
          "contentType": "image/jpeg",
          "sha256": "5bcef1978011ece7788412141fe5e50b6151760b409ea6dee2324d6317deec5d"
        }
      ]
    }
  },
  {
    "game": "one-piece",
    "provider": "optcg-api",
    "providerId": "OP01-025",
    "name": "Roronoa Zoro (025)",
    "setCode": "OP-01",
    "setName": "Romance Dawn",
    "collectorNumber": "OP01-025",
    "language": "English",
    "imageUrl": "https://optcgapi.com/media/static/Card_Images/OP01-025.jpg",
    "thumbnailUrl": "https://optcgapi.com/media/static/Card_Images/OP01-025.jpg",
    "providerCardUrl": "https://optcgapi.com/api/sets/card/OP01-025/",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:34.953Z",
      "images": [
        {
          "url": "https://optcgapi.com/media/static/Card_Images/OP01-025.jpg",
          "width": 600,
          "height": 838,
          "contentType": "image/jpeg",
          "sha256": "e08d9914fdf5e51b6c7dee76c3bbc793c695f1c572fabeded2479e1c78936c98"
        }
      ]
    }
  },
  {
    "game": "one-piece",
    "provider": "optcg-api",
    "providerId": "OP01-016",
    "name": "Nami",
    "setCode": "OP-01",
    "setName": "Romance Dawn",
    "collectorNumber": "OP01-016",
    "language": "English",
    "imageUrl": "https://optcgapi.com/media/static/Card_Images/OP01-016.jpg",
    "thumbnailUrl": "https://optcgapi.com/media/static/Card_Images/OP01-016.jpg",
    "providerCardUrl": "https://optcgapi.com/api/sets/card/OP01-016/",
    "verification": {
      "verifiedAt": "2026-09-09T20:45:35.041Z",
      "images": [
        {
          "url": "https://optcgapi.com/media/static/Card_Images/OP01-016.jpg",
          "width": 600,
          "height": 838,
          "contentType": "image/jpeg",
          "sha256": "7f7e4c957ae2e227a76d8b3fe1ca14ab63625a8312bdb8de34a0049a7d44d687"
        }
      ]
    }
  }
] as const;
