import { test, expect } from '@playwright/test';
import sharp from 'sharp';
const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAHUlEQVQokWP4TyJgGNVABGAgRhEyGNVADKB9KAEAr639H8LdEzEAAAAASUVORK5CYII=','base64');
const front=(name:string)=>({name,mimeType:'image/png',buffer:image});
test.beforeEach(async({request})=>{expect((await request.post('/api/reset-fixture')).ok()).toBe(true);});
test('real local SQL: one front review/removal persists, ten fronts commit once with unchanged destination',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
 await page.goto('/');await page.getByRole('combobox',{name:'Destination storage location',exact:true}).selectOption('scanner-fixture-location');
 await page.getByRole('button',{name:'Create Cloud Batch',exact:true}).click();
 const files=page.getByLabel('Card front images');await expect(files).toBeEnabled();
 await files.setInputFiles(front('review-one.png'));
 await expect(page.getByText('1 scans ready',{exact:true})).toBeVisible();
 await expect(page.getByRole('region',{name:'Upload card scans'}).getByText('1 cards',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Identify Cards',exact:true}).click();
 await expect(page.getByRole('button',{name:'Resolve 1 Items',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Resolve 1 Items',exact:true}).click();
 await page.getByRole('button',{name:'Rotate 90°',exact:true}).click();
 await page.getByRole('button',{name:'Retry recognition',exact:true}).click();
 await expect(page.locator('details[open]').getByRole('button',{name:'Confirm',exact:true})).toBeEnabled();
 await page.locator('details[open]').getByRole('button',{name:'Confirm',exact:true}).click();
 const current=async()=> (await (await request.get('/api/chaos-sort/scans')).json());
 await expect.poll(async()=> (await current()).captures[0].item?.humanState).toBe('confirmed');
 const before=await current();expect(before.physicalCount).toBe(1);expect(before.captures[0].item.rotation).toBe(90);
 await page.reload();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','1');
 if (!await page.getByRole('button',{name:'Remove from Batch',exact:true}).isVisible()) await page.locator('summary').filter({hasText:'Review inspector'}).click();
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Remove from Batch',exact:true}).click();
 await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await page.reload();
 await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');
 const tombstone=(await current()).captures[0];expect(tombstone.status).toBe('REMOVED');
 expect((await request.post('/api/chaos-sort/scans',{data:{action:'review',payload:{batchId:before.album.id,captureId:tombstone.capture_id,revision:tombstone.revision,item:before.captures[0].item}}})).ok()).toBe(false);
 expect((await request.get('/api/chaos-sort/scans?captureId='+tombstone.capture_id)).status()).toBe(404);
 expect(await (await request.get('/api/evidence')).json()).toMatchObject({cards:0,positions:0,events:0});
 const mixed=await Promise.all(Array.from({length:10},async(_,i)=>({name:`front-${i}.png`,mimeType:'image/png',buffer:await sharp({create:{width:16,height:16,channels:3,background:{r:10+i*20,g:50,b:150}}}).png().toBuffer()})));
 await files.setInputFiles(mixed);
 await expect(page.getByText('10 scans ready',{exact:true})).toBeVisible();
 await expect(page.getByRole('region',{name:'Upload card scans'}).getByText('10 cards',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Identify Cards',exact:true}).click();
 await expect(page.getByRole('button',{name:'Commit 10 Cards to Inventory',exact:true})).toBeEnabled();
 await expect.poll(async()=> (await current()).captures.filter((c:{status:string;item?:{humanState:string}})=>c.status!=='REMOVED'&&c.item?.humanState==='confirmed').length).toBe(10);
 await page.reload();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','10');
 const ten=await current();expect(ten.album.destination_id).toBe('scanner-fixture-location');expect(new Set(ten.captures.map((c:{capture_id:string})=>c.capture_id)).size).toBe(11);
 expect(ten.captures.filter((c:{status:string;back_object_path:string|null})=>c.status!=='REMOVED').every((c:{back_object_path:string|null})=>c.back_object_path===null)).toBe(true);
 await page.getByRole('button',{name:'Commit 10 Cards to Inventory',exact:true}).click();
 await expect(page.getByRole('heading',{name:'10 cards added',exact:true})).toBeVisible();
 expect(await (await request.get('/api/evidence')).json()).toMatchObject({cards:10,positions:10,events:10,closed:1});
 expect((await request.post('/api/chaos-sort/scans',{data:{action:'commit',payload:{batchId:ten.album.id}}})).ok()).toBe(true);
 expect(await (await request.get('/api/evidence')).json()).toMatchObject({cards:10,positions:10,events:10});expect(errors).toEqual([]);
});
