import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { money } from "@/lib/showcase";
import { RequestActions } from "@/components/dashboard/showcase/RequestActions";
import { PickQuantity } from "@/components/dashboard/showcase/PickQuantity";

export default async function ShowcaseRequestDetailPage({ params }: { params: Promise<{ requestId: string }> }) {
  const { requestId } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser();
  const { data: preference } = user ? await supabase.from("user_preferences").select("active_workspace_id").eq("user_id", user.id).maybeSingle() : { data: null };
  const { data: request } = preference?.active_workspace_id ? await supabase.from("showcase_requests").select("*,showcase_request_items(*)").eq("id", requestId).eq("workspace_id", preference.active_workspace_id).maybeSingle() : { data: null };
  if (!request) notFound();
  const refs = (request.showcase_request_items ?? []).map((item: { canonical_inventory_ref: string }) => item.canonical_inventory_ref);
  const { data: items } = user && refs.length ? await supabase.from("inventory_items").select("id,card_name,location_id,quantity,data,set_code,collector_number").eq("user_id", user.id).in("id", refs) : { data: [] };
  const locations = user ? (await supabase.from("inventory_locations").select("id,name,data").eq("user_id", user.id)).data ?? [] : [];
  const byId = new Map((items ?? []).map((item) => [item.id, item])); const locationById = new Map(locations.map((location) => [location.id, location]));
  return <main className="dashboard-responsive mx-auto max-w-[1000px] px-4 py-7 sm:px-7"><Link href="/dashboard/showcase/requests" className="text-sm font-semibold text-td-accent-text">← Back to requests</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-td-muted">Request {request.id.slice(0, 8)}</p><h1 className="mt-2 text-3xl font-semibold text-td-primary">{request.customer_name}</h1><p className="mt-2 text-sm text-td-muted">{request.customer_email ?? request.customer_phone ?? "No contact details provided"}</p></div><RequestActions requestId={request.id} status={request.status} /></div><section className="mt-7 space-y-3">{(request.showcase_request_items ?? []).map((line: { id: string; canonical_inventory_ref: string; requested_quantity: number; picked_quantity?: number; unit_price_snapshot: number; line_total: number }) => { const item = byId.get(line.canonical_inventory_ref); const location = item?.location_id ? locationById.get(item.location_id) : null; return <article key={line.id} className="rounded-2xl border border-td-ink/[.08] bg-td-surface/60 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-td-primary">{item?.card_name ?? "Inventory item unavailable"}</h2><p className="mt-1 text-xs text-td-muted">{[item?.set_code, item?.collector_number, item?.data?.condition, item?.data?.finish].filter(Boolean).join(" · ")}</p></div><div className="text-right"><p className="font-semibold text-td-primary">{money(Number(line.line_total))}</p><p className="text-xs text-td-muted">Qty {line.requested_quantity} · {money(Number(line.unit_price_snapshot))} each</p></div></div><div className="mt-4 rounded-xl border border-amber-300/15 bg-amber-300/[.05] p-3 text-sm text-amber-100"><span className="font-semibold">Pick location:</span> {location?.name ?? "No location assigned"}</div>{request.status === "picking" ? <PickQuantity requestId={request.id} itemId={line.id} requested={line.requested_quantity} initial={line.picked_quantity ?? 0} /> : null}</article>; })}</section></main>;
}
