"use client";

import { useEffect, useRef, useState } from "react";
import { Check, FileImage, Loader2, RefreshCw, Search, ShieldCheck, Upload, X } from "lucide-react";

type Asset = { id: string; name: string; asset_type: string; width: number | null; height: number | null; tags: string[]; approval_status: string; signed_url: string | null; storage_path: string; marketing_use_approved: boolean; source: string; license_notes: string; alt_text: string; source_url: string | null; brand_role: string | null; screenshot_role: string | null };
const TYPES = ["logo", "product_screenshot", "feature_screenshot", "card_image", "background", "texture", "device_mockup", "icon", "campaign_artwork", "social_export", "email_export", "other"];

function Preview({ asset, onBroken }: { asset: Asset; onBroken: () => void }) {
  const [broken, setBroken] = useState(false);
  if (!asset.signed_url || broken) return <div className="flex h-full min-h-28 flex-col items-center justify-center gap-2 text-center text-td-muted"><FileImage className="h-9 w-9" /><span className="text-xs">Preview unavailable</span><span className="max-w-full truncate px-3 font-mono text-[10px]">{asset.storage_path}</span></div>;
  return <img src={asset.signed_url} alt={asset.alt_text || asset.name} loading="lazy" className="max-h-full max-w-full object-contain" onError={() => { setBroken(true); onBroken(); }} />;
}

export function AssetVaultWorkspace() {
  const [assets, setAssets] = useState<Asset[]>([]); const [search, setSearch] = useState(""); const [type, setType] = useState(""); const [approval, setApproval] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [syncing, setSyncing] = useState(false); const [selected, setSelected] = useState<Asset | null>(null); const inputRef = useRef<HTMLInputElement>(null);
  async function load() { setLoading(true); const params = new URLSearchParams({ ...(search ? { search } : {}), ...(type ? { type } : {}), ...(approval ? { approval } : {}) }); const response = await fetch(`/api/admin/marketing/assets?${params}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) setMessage(body.error ?? "Asset Vault could not be loaded."); else setAssets(body.assets ?? []); setLoading(false); }
  useEffect(() => { void load(); }, [search, type, approval]);
  async function upload(files: FileList | null) { if (!files?.length) return; setUploading(true); setMessage(""); for (const file of Array.from(files)) { const form = new FormData(); form.append("file", file); form.append("assetType", file.name.toLowerCase().includes("logo") ? "logo" : "other"); const response = await fetch("/api/admin/marketing/assets/upload", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) { setMessage(body.error ?? `${file.name} could not be uploaded.`); break; } } setUploading(false); if (inputRef.current) inputRef.current.value = ""; void load(); }
  async function syncRepoAssets() { setSyncing(true); setMessage(""); const response = await fetch("/api/admin/marketing/assets/register-repo-brand", { method: "POST" }); const body = await response.json(); setMessage(response.ok ? body.message : body.error ?? "Built-in brand assets could not be synced."); setSyncing(false); if (response.ok) void load(); }
  async function approve(asset: Asset) { const response = await fetch(`/api/admin/marketing/assets/${asset.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ approvalStatus: "approved", marketingUseApproved: true }) }); const body = await response.json(); if (!response.ok) setMessage(body.error ?? "Approval failed."); else { setMessage("Asset approved for marketing."); setSelected(null); void load(); } }
  return <div className="mx-auto max-w-[1500px] px-4 py-7 sm:px-8 sm:py-10"><div className="flex flex-col gap-5 border-b border-td-ink/10 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-td-accent">Admin growth engine</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em] text-td-primary">Asset Vault</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-td-secondary">The approved source of truth for Trading Docks creative. Every image keeps its source, license, and review state.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void syncRepoAssets()} disabled={syncing} className="td-button-secondary"><RefreshCw className={`h-4 w-4 ${syncing ? "animate-spin" : ""}`} />{syncing ? "Syncing…" : "Sync Trading Docks brand assets"}</button><label className="td-button-primary cursor-pointer"><Upload className="h-4 w-4" />{uploading ? "Uploading…" : "Upload assets"}<input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" multiple className="sr-only" onChange={(event) => void upload(event.target.files)} /></label></div></div>
    <div className="mt-6 flex flex-col gap-3 rounded-2xl border border-td-ink/10 bg-td-surface/60 p-4 lg:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-td-muted" /><input value={search} onChange={(e) => setSearch(e.target.value)} className="td-input pl-10" placeholder="Search approved visual material" /></label><select value={type} onChange={(e) => setType(e.target.value)} className="td-input lg:w-56"><option value="">All asset types</option>{TYPES.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select><select value={approval} onChange={(e) => setApproval(e.target.value)} className="td-input lg:w-44"><option value="">All review states</option>{["draft", "approved", "restricted", "archived"].map((item) => <option key={item} value={item}>{item}</option>)}</select></div>
    {message ? <p role="status" className="mt-4 rounded-xl border border-td-accent/20 bg-td-accent/10 p-4 text-sm text-td-accent">{message}</p> : null}
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{loading ? <div className="col-span-full flex items-center justify-center p-16 text-sm text-td-muted"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading source material…</div> : assets.length ? assets.map((asset) => <button type="button" key={asset.id} onClick={() => setSelected(asset)} className="group overflow-hidden rounded-2xl border border-td-ink/10 bg-td-surface/60 text-left transition hover:-translate-y-0.5 hover:border-td-accent/40"><div className="flex aspect-[4/3] items-center justify-center bg-td-canvas p-4"><Preview asset={asset} onBroken={() => undefined} /></div><div className="p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold text-td-primary">{asset.name}</p><p className="mt-1 text-xs capitalize text-td-muted">{asset.asset_type.replaceAll("_", " ")} {asset.width && asset.height ? `· ${asset.width}×${asset.height}` : ""}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase tracking-wide ${asset.approval_status === "approved" ? "bg-td-success/10 text-td-success" : "bg-td-warning/10 text-td-warning"}`}>{asset.approval_status}</span></div>{asset.brand_role ? <p className="mt-2 text-xs text-td-accent">{asset.brand_role.replaceAll("_", " ")}</p> : null}{asset.tags?.length ? <p className="mt-2 truncate text-xs text-td-muted">{asset.tags.join(" · ")}</p> : null}</div></button>) : <div className="col-span-full rounded-2xl border border-dashed border-td-ink/15 p-16 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-td-accent" /><p className="mt-4 font-semibold text-td-primary">No assets match this view</p><p className="mt-2 text-sm text-td-muted">Upload a real Trading Docks screenshot or register an owned brand asset to begin.</p></div>}</div>
    {selected ? <div className="fixed inset-0 z-50 flex justify-end bg-black/50" role="dialog" aria-modal="true"><div className="h-full w-full max-w-lg overflow-y-auto border-l border-td-ink/10 bg-td-surface p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-td-accent">Asset review</p><h2 className="mt-2 text-2xl font-semibold text-td-primary">{selected.name}</h2></div><button type="button" onClick={() => setSelected(null)} className="td-button-secondary" aria-label="Close detail panel"><X className="h-4 w-4" /></button></div><div className="mt-6 flex min-h-44 items-center justify-center rounded-xl bg-td-canvas p-5"><Preview asset={selected} onBroken={() => undefined} /></div><dl className="mt-6 space-y-4 text-sm"><div><dt className="td-label">Type</dt><dd className="mt-1 capitalize text-td-secondary">{selected.asset_type.replaceAll("_", " ")}</dd></div><div><dt className="td-label">Brand role</dt><dd className="mt-1 text-td-secondary">{selected.brand_role?.replaceAll("_", " ") || "Not assigned"}</dd></div>{selected.screenshot_role ? <div><dt className="td-label">Screenshot role</dt><dd className="mt-1 capitalize text-td-secondary">{selected.screenshot_role}</dd></div> : null}<div><dt className="td-label">Public/storage path</dt><dd className="mt-1 break-all font-mono text-xs text-td-secondary">{selected.storage_path}</dd></div><div><dt className="td-label">Source</dt><dd className="mt-1 text-td-secondary">{selected.source}{selected.source_url ? ` · ${selected.source_url}` : ""}</dd></div><div><dt className="td-label">License notes</dt><dd className="mt-1 whitespace-pre-wrap text-td-secondary">{selected.license_notes || "Licensing notes not recorded."}</dd></div></dl>{selected.approval_status !== "approved" ? <button type="button" onClick={() => void approve(selected)} className="td-button-primary mt-8 w-full"><Check className="h-4 w-4" />Approve for marketing</button> : <p className="mt-8 flex items-center gap-2 rounded-xl bg-td-success/10 p-4 text-sm text-td-success"><Check className="h-4 w-4" />Approved for marketing use</p>}</div></div> : null}</div>;
}
