"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Check, FileImage, FlaskConical, Lightbulb, Loader2, Mail, Palette, Plus, Send, ShieldCheck, Sparkles, Target, Users } from "lucide-react";

type Feature = { id: string; slug: string; name: string; customer_description: string; relevant_cta: string; landing_url?: string | null };
type Campaign = { id: string; name: string; status: string; audience: string; objective: string; created_at: string };
type Draft = { id: string; prospect_id: string; subject: string; status: string; created_at: string; marketing_prospects?: { business_name?: string; public_email?: string | null; city?: string; state?: string } | Array<{ business_name?: string; public_email?: string | null; city?: string; state?: string }> };
type GrowthData = { features: Feature[]; campaigns: Campaign[]; drafts: Draft[]; settings: { email_provider: string; outbound_enabled: boolean } };

async function loadGrowth(): Promise<GrowthData> {
  const response = await fetch("/api/admin/marketing/growth", { cache: "no-store" });
  const body = await response.json() as GrowthData & { error?: string };
  if (!response.ok) throw new Error(body.error ?? "Marketing data could not be loaded.");
  return body;
}

export function GrowthDashboard() {
  const [data, setData] = useState<GrowthData | null>(null); const [error, setError] = useState("");
  useEffect(() => { void loadGrowth().then(setData).catch((e: Error) => setError(e.message)); }, []);
  const drafts = data?.drafts ?? [];
  const metrics = [["Campaigns", data?.campaigns.length ?? 0, Target], ["Needs review", drafts.filter((item) => item.status === "draft").length, FileImage], ["Approved", drafts.filter((item) => item.status === "approved").length, Check], ["Mock sent", drafts.filter((item) => item.status === "sent").length, Send]] as const;
  return <GrowthShell title="Marketing" eyebrow="Admin growth engine" description="Discover the right stores, understand their needs, and prepare thoughtful outreach with human approval at every send boundary." actions={<Link href="/dashboard/admin/marketing/store-finder" className="td-button-primary"><Users className="h-4 w-4" />Find prospects</Link>}>
    {error ? <ErrorNotice message={error} /> : null}
    <Link href="/dashboard/admin/marketing/intelligence" className="mt-6 flex items-center justify-between rounded-2xl border border-td-accent/20 bg-td-accent/[.04] p-5 hover:border-td-accent/50"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-td-accent">Strategist tool</p><h2 className="mt-1 text-lg font-semibold text-td-primary">Find the next campaign</h2><p className="mt-1 text-sm text-td-secondary">Rank approved product opportunities using canonical proof and synthetic demo state.</p></div><ArrowRight className="h-5 w-5 text-td-accent" /></Link>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-td-ink/10 bg-td-surface/60 p-5"><Icon className="h-5 w-5 text-td-accent" /><p className="mt-5 text-3xl font-semibold text-td-primary">{value}</p><p className="mt-1 text-sm text-td-muted">{label}</p></div>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-td-ink/10 bg-td-surface/60 p-6"><SectionHeading icon={Sparkles} title="The operating loop" detail="Every recommendation retains its source and stays reviewable." /><div className="mt-6 grid gap-3 sm:grid-cols-2">{[["Discover", "Store Finder", "/dashboard/admin/marketing/store-finder"], ["Understand", "Prospects", "/dashboard/admin/marketing/prospects"], ["Create", "Creative Studio", "/dashboard/admin/marketing/creative-studio"], ["Review", "Outreach queue", "/dashboard/admin/marketing/outreach"], ["Respond", "Sales inbox", "/dashboard/admin/marketing/inbox"]].map(([eyebrow, label, href]) => <Link key={href} href={href} className="group rounded-xl border border-td-ink/10 bg-td-ink/[.02] p-4 hover:border-td-accent/30"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-td-accent">{eyebrow}</p><p className="mt-2 flex items-center justify-between text-sm font-semibold text-td-primary">{label}<ArrowRight className="h-4 w-4 text-td-muted transition group-hover:translate-x-1 group-hover:text-td-accent" /></p></Link>)}</div></section><section className="rounded-2xl border border-td-success/15 bg-td-success/[.035] p-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-td-success">Safe by default</p><h2 className="mt-2 text-xl font-semibold text-td-primary">Human-approved outreach</h2><p className="mt-3 text-sm leading-6 text-td-secondary">Generation is deterministic until a model provider is configured. Sending is mock-only, suppression-aware, idempotent, and never contacts a business from this foundation.</p><div className="mt-5 space-y-3 text-sm text-td-secondary"><p>✓ Feature claims come from the library</p><p>✓ Drafts require explicit approval</p><p>✓ Mock provider is the only active provider</p><p>✓ Production email remains disabled</p></div></section></div>
  </GrowthShell>;
}

export function CampaignWorkspace() {
  const [data, setData] = useState<GrowthData | null>(null); const [name, setName] = useState(""); const [featureId, setFeatureId] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void loadGrowth().then((value) => { setData(value); setFeatureId(value.features[0]?.id ?? ""); }).catch((e: Error) => setMessage(e.message)); }, []);
  async function createCampaign() { setSaving(true); setMessage(""); const response = await fetch("/api/admin/marketing/growth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create_campaign", name, featureId }) }); const body = await response.json() as { error?: string; campaign?: Campaign }; if (!response.ok) setMessage(body.error ?? "Campaign could not be created."); else { setMessage("Campaign saved as draft."); setName(""); setData((current) => current ? { ...current, campaigns: [body.campaign!, ...current.campaigns] } : current); } setSaving(false); }
  return <GrowthShell title="Campaigns" eyebrow="Admin growth engine" description="Campaigns connect an approved Trading Docks feature to a clear audience, objective, CTA, and creative brief." actions={<Link href="/dashboard/admin/marketing/creative-studio" className="td-button-secondary"><Palette className="h-4 w-4" />Creative Studio</Link>}><div className="grid gap-6 xl:grid-cols-[.75fr_1.25fr]"><section className="rounded-2xl border border-td-ink/10 bg-td-surface/60 p-6"><SectionHeading icon={Plus} title="New campaign" detail="Start with a real feature claim." /><label className="mt-6 block"><span className="td-label">Campaign name</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Sort the Chaos" className="td-input mt-2" /></label><label className="mt-4 block"><span className="td-label">Feature</span><select value={featureId} onChange={(e) => setFeatureId(e.target.value)} className="td-input mt-2">{(data?.features ?? []).map((feature) => <option key={feature.id} value={feature.id}>{feature.name}</option>)}</select></label><button type="button" disabled={saving || !name || !featureId} onClick={() => void createCampaign()} className="td-button-primary mt-5 w-full">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Create draft campaign</button>{message ? <p role="status" className="mt-4 rounded-xl bg-td-accent/10 p-3 text-sm text-td-accent">{message}</p> : null}</section><section className="rounded-2xl border border-td-ink/10 bg-td-surface/60 p-6"><SectionHeading icon={Target} title="Campaign library" detail="No performance is fabricated before delivery events exist." /><div className="mt-5 space-y-3">{data?.campaigns.length ? data.campaigns.map((campaign) => <Link href={`/dashboard/admin/marketing/campaigns/${campaign.id}`} key={campaign.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-td-ink/10 p-4 hover:border-td-accent/40"><div><p className="font-semibold text-td-primary">{campaign.name}</p><p className="mt-1 text-xs text-td-muted">{campaign.audience} · {campaign.objective}</p></div><span className="rounded-full bg-td-accent/10 px-2.5 py-1 text-xs font-semibold text-td-accent">{campaign.status}</span></Link>) : <EmptyState title="No campaigns yet" copy="Create a campaign after reviewing a prospect and selecting a feature." />}</div></section></div></GrowthShell>;
}

export function CreativeStudio() {
  const [data, setData] = useState<GrowthData | null>(null); const [prospectId, setProspectId] = useState(""); const [featureId, setFeatureId] = useState(""); const [result, setResult] = useState<{ campaignId?: string; brief?: Record<string, unknown>; draft?: { subject: string } } | null>(null); const [message, setMessage] = useState(""); const [working, setWorking] = useState(false);
  async function generate() { setWorking(true); setMessage(""); const response = await fetch("/api/admin/marketing/creative", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "generate", prospectId, featureId }) }); const body = await response.json(); if (!response.ok) setMessage(body.error ?? "Generation failed."); else setResult(body); setWorking(false); }
  useEffect(() => { void loadGrowth().then((value) => { setData(value); setFeatureId(value.features[0]?.id ?? ""); }).catch((e: Error) => setMessage(e.message)); }, []);
  return <GrowthShell title="Creative Studio" eyebrow="Admin growth engine" description="Generate a structured brief and restrained email concept from approved product facts. The foundation stores the brief before any asset is rendered." actions={<Link href="/dashboard/admin/marketing/brand-system" className="td-button-secondary"><Lightbulb className="h-4 w-4" />Brand System</Link>}><section className="rounded-2xl border border-td-ink/10 bg-td-surface/60 p-6"><SectionHeading icon={Palette} title="Brief generator" detail="No arbitrary image prompt is sent. Composition and claims stay controlled." /><div className="mt-6 grid gap-4 md:grid-cols-2"><label><span className="td-label">Prospect ID</span><input value={prospectId} onChange={(e) => setProspectId(e.target.value)} placeholder="Paste a saved prospect ID" className="td-input mt-2" /></label><label><span className="td-label">Feature</span><select value={featureId} onChange={(e) => setFeatureId(e.target.value)} className="td-input mt-2">{(data?.features ?? []).map((feature) => <option key={feature.id} value={feature.id}>{feature.name}</option>)}</select></label></div><button type="button" disabled={working || !prospectId || !featureId} onClick={() => void generate()} className="td-button-primary mt-5">{working ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}Generate brief and draft</button>{message ? <ErrorNotice message={message} /> : null}</section>{result ? <section className="mt-6 rounded-2xl border border-td-success/15 bg-td-success/[.035] p-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-td-success">Saved for review</p><h2 className="mt-2 text-xl font-semibold text-td-primary">{result.draft?.subject}</h2><pre className="mt-5 overflow-x-auto whitespace-pre-wrap rounded-xl bg-black/20 p-4 text-xs leading-5 text-td-secondary">{JSON.stringify(result.brief, null, 2)}</pre><Link href="/dashboard/admin/marketing/outreach" className="td-button-secondary mt-5 inline-flex">Open outreach queue <ArrowRight className="h-4 w-4" /></Link></section> : null}</GrowthShell>;
}

export function OutreachQueue() {
  const [drafts, setDrafts] = useState<Draft[]>([]); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/marketing/outreach", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setDrafts(body.drafts ?? []); }
  useEffect(() => { void load().catch((e: Error) => setMessage(e.message)); }, []);
  async function action(draftId: string, actionName: "approve" | "reject" | "mock_send") { const response = await fetch(actionName === "mock_send" ? "/api/admin/marketing/outreach" : "/api/admin/marketing/outreach", { method: actionName === "mock_send" ? "POST" : "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draftId, action: actionName }) }); const body = await response.json(); setMessage(body.error ?? (actionName === "mock_send" ? "Mock send recorded. No email was delivered." : `Draft ${actionName}d.`)); if (response.ok) void load(); }
  return <GrowthShell title="Outreach" eyebrow="Admin growth engine" description="Review every draft before it enters the development-safe mock queue. Replies, bounces, and suppression states remain attributable." actions={<Link href="/dashboard/admin/marketing/creative-studio" className="td-button-primary"><Sparkles className="h-4 w-4" />Generate draft</Link>}><div className="mb-5 rounded-xl border border-td-warning/20 bg-td-warning/[.05] p-4 text-sm leading-6 text-td-secondary"><strong className="text-td-warning">Mock-only delivery.</strong> This environment records approved sends but never contacts a business. A real provider cannot be enabled from this foundation.</div>{message ? <p role="status" className="mb-5 rounded-xl bg-td-accent/10 p-4 text-sm text-td-accent">{message}</p> : null}<section className="overflow-x-auto rounded-2xl border border-td-ink/10 bg-td-surface/60">{drafts.length ? <table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-td-ink/10 text-xs uppercase tracking-[.14em] text-td-muted"><tr><th className="px-5 py-4">Subject</th><th className="px-5 py-4">Prospect</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Actions</th></tr></thead><tbody>{drafts.map((draft) => { const prospect = Array.isArray(draft.marketing_prospects) ? draft.marketing_prospects[0] : draft.marketing_prospects; return <tr key={draft.id} className="border-b border-td-ink/[.06] last:border-0"><td className="px-5 py-4 font-semibold text-td-primary">{draft.subject}<p className="mt-1 text-xs font-normal text-td-muted">{prospect?.public_email ?? "No public email"}</p></td><td className="px-5 py-4 text-td-secondary">{prospect?.business_name ?? draft.prospect_id}</td><td className="px-5 py-4"><span className="rounded-full bg-td-accent/10 px-2.5 py-1 text-xs font-semibold text-td-accent">{draft.status}</span></td><td className="px-5 py-4"><div className="flex flex-wrap gap-2">{draft.status === "draft" ? <button type="button" onClick={() => void action(draft.id, "approve")} className="td-button-secondary">Approve</button> : null}{draft.status === "approved" ? <button type="button" onClick={() => void action(draft.id, "mock_send")} className="td-button-primary">Mock send</button> : null}{draft.status === "draft" ? <button type="button" onClick={() => void action(draft.id, "reject")} className="td-button-secondary">Reject</button> : null}</div></td></tr>; })}</tbody></table> : <EmptyState title="No outreach drafts" copy="Generate a prospect-specific brief from Creative Studio, then review it here." />}</section></GrowthShell>;
}

export function MarketingPlaceholder({ title, detail, icon: Icon = ShieldCheck }: { title: string; detail: string; icon?: typeof ShieldCheck }) { return <GrowthShell title={title} eyebrow="Admin growth engine" description={detail}><section className="rounded-2xl border border-td-ink/10 bg-td-surface/60 p-8"><Icon className="h-7 w-7 text-td-accent" /><h2 className="mt-5 text-xl font-semibold text-td-primary">Foundation ready</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-td-secondary">This surface is intentionally honest about what is implemented. It is wired to the admin-only growth schema and can be extended without replacing the prospect, provenance, suppression, or approval model.</p></section></GrowthShell>; }

function SectionHeading({ icon: Icon, title, detail }: { icon: typeof ShieldCheck; title: string; detail: string }) { return <div className="flex items-start gap-3"><Icon className="mt-0.5 h-5 w-5 text-td-accent" /><div><h2 className="text-lg font-semibold text-td-primary">{title}</h2><p className="mt-1 text-sm text-td-muted">{detail}</p></div></div>; }
function EmptyState({ title, copy }: { title: string; copy: string }) { return <div className="rounded-xl border border-dashed border-td-ink/15 p-8 text-center"><Mail className="mx-auto h-6 w-6 text-td-muted" /><p className="mt-3 font-semibold text-td-primary">{title}</p><p className="mt-1 text-sm text-td-muted">{copy}</p></div>; }
function ErrorNotice({ message }: { message: string }) { return <p role="alert" className="mt-4 rounded-xl border border-td-danger/20 bg-td-danger/10 p-4 text-sm text-td-danger">{message}</p>; }
function GrowthShell({ title, eyebrow, description, actions, children }: { title: string; eyebrow: string; description: string; actions?: React.ReactNode; children: React.ReactNode }) { return <div className="mx-auto max-w-[1500px] px-4 py-7 sm:px-8 sm:py-10"><div className="flex flex-col gap-5 border-b border-td-ink/10 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-td-accent">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.03em] text-td-primary">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-td-secondary">{description}</p></div>{actions ? <div className="flex shrink-0 gap-2">{actions}</div> : null}</div><div className="pt-7">{children}</div></div>; }
