"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Loader2, Search } from "lucide-react";

type Prospect = Record<string, unknown>;
export function ProspectDetail({ prospect }: { prospect: Prospect }) {
  const [message, setMessage] = useState(""); const [working, setWorking] = useState(false);
  async function discover() { setWorking(true); setMessage(""); const response = await fetch("/api/admin/marketing/contact-discovery", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prospectId: prospect.id }) }); const data = await response.json(); setMessage(data.message ?? data.error ?? "Contact discovery completed."); setWorking(false); }
  return <div className="mx-auto max-w-5xl px-4 py-8 sm:px-8"><Link href="/dashboard/admin/marketing/prospects" className="inline-flex items-center gap-2 text-sm text-td-accent"><ArrowLeft className="h-4 w-4" />Back to prospects</Link><div className="mt-6 flex flex-col gap-5 border-b border-td-ink/10 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-td-accent">Prospect detail</p><h1 className="mt-2 text-3xl font-semibold text-td-primary">{String(prospect.business_name ?? "Prospect")}</h1><p className="mt-2 text-sm text-td-secondary">{[prospect.city, prospect.state, prospect.postal_code].filter(Boolean).join(", ") || String(prospect.address ?? "")}</p></div><button type="button" disabled={working || !prospect.website_url} onClick={() => void discover()} className="td-button-primary">{working ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}Discover public contact</button></div>{message ? <p className="mt-5 rounded-xl bg-td-accent/10 p-4 text-sm text-td-accent">{message}</p> : null}<div className="mt-6 grid gap-5 sm:grid-cols-2"><section className="rounded-2xl border border-td-ink/10 bg-td-surface/60 p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-td-muted">Business contact</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-td-muted">Phone</dt><dd className="mt-1 text-td-primary">{String(prospect.phone ?? "Not available")}</dd></div><div><dt className="text-td-muted">Website</dt><dd className="mt-1 break-all text-td-primary">{String(prospect.website_url ?? "Not available")}</dd></div><div><dt className="text-td-muted">Public email</dt><dd className="mt-1 text-td-primary">{String(prospect.public_email ?? "No public email found")}</dd></div></dl></section><section className="rounded-2xl border border-td-ink/10 bg-td-surface/60 p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-td-muted">CRM state</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-td-muted">Status</dt><dd className="mt-1 text-td-primary">{String(prospect.status ?? "New")}</dd></div><div><dt className="text-td-muted">Suppression</dt><dd className="mt-1 text-td-primary">{prospect.suppressed ? "Do not contact" : "Not suppressed"}</dd></div><div><dt className="text-td-muted">Notes</dt><dd className="mt-1 whitespace-pre-wrap text-td-primary">{String(prospect.notes ?? "No notes yet")}</dd></div></dl></section></div></div>;
}
