import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { PropsWithChildren } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { color, elevation, radius, space, type } from '@/design';

export function AdminTopBar({ title, eyebrow='COMMAND CENTER', back=false }: { title:string; eyebrow?:string; back?:boolean }) {
  return <View style={s.top}><View style={s.topLeft}>{back?<Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={20} color={color.text}/></Pressable>:null}<View><Text style={s.eyebrow}>{eyebrow}</Text><Text style={s.title}>{title}</Text></View></View><View style={s.secure}><Ionicons name="shield-checkmark" size={14} color={color.success}/><Text style={s.secureText}>SECURE</Text></View></View>;
}
export function MetricCard({ label, value, note, icon, tone='blue' }: { label:string; value:string|number; note:string; icon:keyof typeof Ionicons.glyphMap; tone?:'blue'|'green'|'amber'|'red' }) {
  const accent=tone==='green'?color.success:tone==='amber'?color.warning:tone==='red'?color.danger:color.primaryBright;
  return <View style={s.metric}><View style={[s.metricIcon,{backgroundColor:accent+'18'}]}><Ionicons name={icon} size={20} color={accent}/></View><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text><Text style={s.metricNote}>{note}</Text></View>;
}
export function AdminPanel({ children, style }: PropsWithChildren<{style?:object}>){return <View style={[s.panel,style]}>{children}</View>}
export function AdminRow({ icon, title, subtitle, onPress, badge }: { icon:keyof typeof Ionicons.glyphMap; title:string; subtitle:string; onPress?:()=>void; badge?:string }) {
 return <Pressable onPress={onPress} style={({pressed})=>[s.row,pressed&&{opacity:.72}]}><View style={s.rowIcon}><Ionicons name={icon} size={19} color={color.primaryBright}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowSub}>{subtitle}</Text></View>{badge?<Text style={s.badge}>{badge}</Text>:null}<Ionicons name="chevron-forward" size={18} color={color.textMuted}/></Pressable>
}
const s=StyleSheet.create({top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:space.md},topLeft:{flexDirection:'row',alignItems:'center',gap:space.sm},back:{width:42,height:42,borderRadius:radius.md,backgroundColor:color.surface,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:color.border},eyebrow:{...type.label,color:color.primaryBright},title:{...type.heading,color:color.text,marginTop:3},secure:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:color.success+'12',borderRadius:radius.pill,paddingHorizontal:10,paddingVertical:7},secureText:{color:color.success,fontWeight:'900',fontSize:9,letterSpacing:1},metric:{flex:1,minWidth:150,backgroundColor:color.surface,borderRadius:radius.xl,borderWidth:1,borderColor:color.border,padding:space.md,...elevation.raised},metricIcon:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center'},metricLabel:{...type.label,color:color.textMuted,marginTop:space.md},metricValue:{color:color.text,fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:5},metricNote:{...type.caption,color:color.textSecondary,marginTop:4},panel:{backgroundColor:color.surface,borderRadius:radius.xl,borderWidth:1,borderColor:color.border,overflow:'hidden'},row:{minHeight:76,flexDirection:'row',alignItems:'center',gap:space.sm,paddingHorizontal:space.md,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:color.border},rowIcon:{width:40,height:40,borderRadius:14,backgroundColor:color.primary+'18',alignItems:'center',justifyContent:'center'},rowTitle:{color:color.text,fontWeight:'900',fontSize:14},rowSub:{color:color.textMuted,fontSize:11,lineHeight:16,marginTop:3},badge:{color:color.primaryBright,fontWeight:'900',fontSize:10,backgroundColor:color.primary+'18',paddingHorizontal:9,paddingVertical:5,borderRadius:radius.pill}});
