import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Logo } from '@/components/primitives';
import { PrimaryButton, Surface } from '@/components/foundation';
import { color, radius, space, type } from '@/design';
import { supabase } from '@/lib/supabase';
import { signInSocial } from '@/lib/oauth';

export default function Auth(){
  const [signup,setSignup]=useState(false); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [showPassword,setShowPassword]=useState(false);
  const submit=async()=>{if(!supabase)return Alert.alert('Supabase is not configured','Add the mobile environment variables and restart Expo.');if(!email||password.length<6)return Alert.alert('Check your details','Use a valid email and a password with at least 6 characters.');setBusy(true);const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(r.error)return Alert.alert(signup?'Account not created':'Sign in failed',r.error.message);if(signup&&!r.data.session)return Alert.alert('Check your inbox','Confirm your email, then return to sign in.');router.replace('/(tabs)');};
  const magic=async()=>{if(!supabase||!email)return Alert.alert('Enter your email','We will send a secure sign-in link.');setBusy(true);const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:'tradingdocks://auth/callback'}});setBusy(false);if(error)return Alert.alert('Link not sent',error.message);Alert.alert('Check your inbox','Your secure Trading Docks sign-in link is on its way.');};
  const social=async(provider:'google'|'apple')=>{try{setBusy(true);const ok=await signInSocial(provider);if(ok)router.replace('/(tabs)')}catch(e){Alert.alert('Social sign-in unavailable',e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}};
  return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.wrap} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="chevron-back" size={22} color={color.text}/></Pressable><Logo/><View><Text style={s.kicker}>{signup?'CREATE YOUR ACCOUNT':'WELCOME BACK'}</Text><Text style={s.title}>{signup?'One account for every Trading Docks workspace.':'Your cards, sessions, and workspace are waiting.'}</Text><Text style={s.sub}>Securely continue across Trading Docks mobile and web.</Text></View><View style={s.socials}><Pressable onPress={()=>social('google')} disabled={busy} style={s.social}><Ionicons name="logo-google" size={20} color={color.text}/><Text style={s.socialText}>Continue with Google</Text></Pressable>{Platform.OS==='ios'&&<Pressable onPress={()=>social('apple')} disabled={busy} style={[s.social,s.apple]}><Ionicons name="logo-apple" size={21} color="#000"/><Text style={[s.socialText,{color:'#000'}]}>Continue with Apple</Text></Pressable>}</View><View style={s.or}><View style={s.rule}/><Text style={s.orText}>OR CONTINUE SECURELY</Text><View style={s.rule}/></View><Surface style={s.panel} tone="raised"><View style={s.input}><Ionicons name="mail-outline" size={19} color={color.textMuted}/><TextInput value={email} onChangeText={setEmail} placeholder="Email address" placeholderTextColor={color.textMuted} autoCapitalize="none" keyboardType="email-address" style={s.field}/></View><View style={s.input}><Ionicons name="lock-closed-outline" size={19} color={color.textMuted}/><TextInput value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor={color.textMuted} secureTextEntry={!showPassword} style={s.field}/><Pressable onPress={()=>setShowPassword(v=>!v)}><Ionicons name={showPassword?'eye-off-outline':'eye-outline'} size={20} color={color.textMuted}/></Pressable></View><PrimaryButton label={signup?'Create account':'Sign in'} busy={busy} onPress={submit}/><Pressable onPress={magic}><Text style={s.magic}>Email me a secure sign-in link</Text></Pressable><Pressable onPress={()=>setSignup(v=>!v)}><Text style={s.switch}>{signup?'Already have an account? Sign in':'New here? Create a Trading Docks account'}</Text></Pressable></Surface><View style={s.trust}><Ionicons name="shield-checkmark-outline" size={16} color={color.success}/><Text style={s.trustText}>Your password and provider credentials are never stored by Trading Docks.</Text></View><Pressable onPress={()=>router.replace('/(tabs)')}><Text style={s.preview}>Continue in preview mode</Text></Pressable></ScrollView></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:color.canvas},wrap:{padding:space.lg,paddingBottom:space.xxl,gap:space.lg},back:{width:44,height:44,borderRadius:radius.md,backgroundColor:color.surface,borderWidth:1,borderColor:color.border,alignItems:'center',justifyContent:'center'},kicker:{...type.label,color:color.primaryBright,marginBottom:space.sm},title:{...type.display,color:color.text},sub:{...type.body,color:color.textSecondary,marginTop:space.sm},socials:{gap:space.sm},social:{height:58,borderRadius:radius.md,backgroundColor:color.surface,borderWidth:1,borderColor:color.border,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},apple:{backgroundColor:'#fff',borderColor:'#fff'},socialText:{color:color.text,fontWeight:'900',fontSize:14},or:{flexDirection:'row',alignItems:'center',gap:10},rule:{height:1,backgroundColor:color.border,flex:1},orText:{color:color.textMuted,fontSize:9,fontWeight:'900',letterSpacing:1.1},panel:{gap:space.sm,padding:space.md},input:{height:57,borderRadius:radius.md,borderColor:color.border,borderWidth:1,backgroundColor:color.canvasRaised,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:15},field:{flex:1,color:color.text,fontSize:15},magic:{color:color.primaryBright,textAlign:'center',fontWeight:'800',fontSize:12,paddingVertical:5},switch:{color:color.textSecondary,textAlign:'center',fontWeight:'800',fontSize:12,paddingVertical:5},trust:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,paddingHorizontal:12},trustText:{...type.caption,color:color.textMuted,flex:1},preview:{color:color.textMuted,textAlign:'center',fontSize:12,fontWeight:'700'}});
