"use client";

import { useMemo, useState } from "react";
import { Search, ShoppingBag, Sparkles, X } from "lucide-react";
import type { ShowcaseCard } from "@/lib/showcase";

function money(value: number | null | undefined) {
  return typeof value === "number" && Number.isFinite(value) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value) : "Price on request";
}

export function ShowcasePublicExperience({ slug, profile, cards, initialQuery }: { slug: string; profile: Record<string, any>; cards: ShowcaseCard[]; initialQuery: string }) {
  const [query, setQuery] = useState(initialQuery);
  const [cart, setCart] = useState<Record<string, number>>({});
  const [cartOpen, setCartOpen] = useState(false);
  const [customerName, setCustomerName] = useState("");
  const [submitState, setSubmitState] = useState<string | null>(null);
  const selected = useMemo(() => cards.filter((card) => cart[card.public_id]), [cards, cart]);
  const total = selected.reduce((sum, card) => sum + (card.public_price ?? 0) * (cart[card.public_id] ?? 0), 0);
  function submitSearch(event: React.FormEvent) { event.preventDefault(); window.location.href = `/s/${slug}?q=${encodeURIComponent(query)}`; }
  async function submitRequest() { if (!customerName.trim()) { setSubmitState("Enter your name to continue."); return; } setSubmitState("Submitting…"); const response = await fetch("/api/showcase/requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ slug, customerName, items: selected.map((card) => ({ public_id: card.public_id, quantity: cart[card.public_id] })) }) }); const result = await response.json(); if (!response.ok) { setSubmitState(result.error ?? "Please try again."); return; } setSubmitState(`Request ${String(result.requestId).slice(0, 8)} sent. Please see the counter.`); setCart({}); }
  return <main className="min-h-screen bg-[#071017] text-white">
    <header className="border-b border-white/10 bg-[#0b1821] px-4 py-5 sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3">{profile.logo_url ? <img src={profile.logo_url} alt="" className="h-11 w-11 rounded-xl object-cover" /> : <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-cyan-300/15 text-cyan-200"><Sparkles className="h-5 w-5" /></div>}<div className="min-w-0"><p className="truncate text-base font-semibold">{profile.display_name}</p><p className="text-xs text-white/50">Trading Docks Showcase</p></div></div><button onClick={() => setCartOpen(true)} className="relative flex h-11 items-center gap-2 rounded-xl border border-white/10 px-3 text-sm font-semibold hover:bg-white/5"><ShoppingBag className="h-4 w-4 text-cyan-200" />Request{selected.length ? <span className="rounded-full bg-cyan-300 px-2 py-0.5 text-xs text-slate-950">{selected.length}</span> : null}</button></div></header>
    <section className="mx-auto max-w-7xl px-4 pb-7 pt-10 sm:px-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-200">Live inventory</p><h1 className="mt-3 max-w-3xl text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Find your next card.</h1>{profile.description ? <p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">{profile.description}</p> : null}<form onSubmit={submitSearch} className="mt-7 flex max-w-2xl items-center gap-2 rounded-2xl border border-white/15 bg-white/[.05] p-2"><Search className="ml-2 h-5 w-5 text-white/40" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by card, set, or collector number" className="min-w-0 flex-1 bg-transparent px-2 py-3 text-sm outline-none placeholder:text-white/35" /><button className="rounded-xl bg-cyan-300 px-4 py-3 text-sm font-bold text-slate-950">Search</button></form></section>
    <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-8"><div className="mb-4 flex items-center justify-between"><p className="text-sm text-white/50">{cards.length ? `${cards.length} cards available` : "No cards match this search"}</p><p className="text-xs text-white/35">Prices shown when provided by the store</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-6">{cards.map((card) => <article key={card.public_id} className="group overflow-hidden rounded-2xl border border-white/10 bg-white/[.045]"><div className="aspect-[.72] bg-[#0d202b]">{card.image_url ? <img src={card.image_url} alt={card.name} className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.02]" /> : <div className="flex h-full items-center justify-center px-4 text-center text-sm text-white/35">Image unavailable</div>}</div><div className="p-3"><h2 className="truncate text-sm font-semibold">{card.name}</h2><p className="mt-1 truncate text-xs text-white/45">{[card.set_name ?? card.set_code, card.collector_number, card.condition].filter(Boolean).join(" · ") || "Card"}</p><div className="mt-3 flex items-center justify-between gap-2"><span className="text-sm font-semibold text-cyan-100">{profile.show_prices ? money(card.public_price) : "Ask in store"}</span><button disabled={!profile.allow_requests} onClick={() => setCart((prev) => ({ ...prev, [card.public_id]: Math.min(card.sellable_quantity, (prev[card.public_id] ?? 0) + 1) }))} className="rounded-lg bg-cyan-300 px-2.5 py-2 text-xs font-bold text-slate-950 disabled:opacity-40">Add</button></div>{profile.show_quantities ? <p className="mt-2 text-[11px] text-white/35">{card.sellable_quantity} available</p> : null}</div></article>)}</div></section>
    {cartOpen ? <div className="fixed inset-0 z-50 bg-black/70 p-4 sm:p-8"><aside className="ml-auto flex h-full w-full max-w-md flex-col rounded-3xl border border-white/10 bg-[#0b1821] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-cyan-200">Customer request</p><h2 className="mt-1 text-xl font-semibold">Your cards</h2></div><button onClick={() => setCartOpen(false)} aria-label="Close request"><X /></button></div><div className="mt-6 flex-1 space-y-3 overflow-y-auto">{selected.length ? selected.map((card) => <div key={card.public_id} className="flex items-center gap-3 rounded-xl border border-white/10 p-3"><div className="h-14 w-10 overflow-hidden rounded bg-black/20">{card.image_url ? <img src={card.image_url} alt="" className="h-full w-full object-cover" /> : null}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{card.name}</p><p className="text-xs text-white/45">Qty {cart[card.public_id]} · {money(card.public_price)}</p></div><button onClick={() => setCart((prev) => { const next = { ...prev }; delete next[card.public_id]; return next; })} className="text-xs text-white/45">Remove</button></div>) : <p className="rounded-2xl border border-dashed border-white/15 p-6 text-center text-sm text-white/45">Add cards to start a request.</p>}</div><div className="border-t border-white/10 pt-4"><div className="flex justify-between text-sm"><span className="text-white/50">Estimated total</span><strong>{money(total)}</strong></div><button disabled={!selected.length || !profile.allow_requests} className="mt-4 w-full rounded-xl bg-cyan-300 py-3 text-sm font-bold text-slate-950 disabled:opacity-40">Continue request</button><p className="mt-3 text-center text-xs text-white/35">No payment is collected in Showcase V1.</p></div></aside></div> : null}
  </main>;
}
