-- READ ONLY. Run within installation transaction before commit, then again after commit.
begin read only;
set local search_path=public;
select count(*) inventory_rows,sum(quantity) inventory_units,count(*) filter(where workspace_id is null) unscoped from public.inventory_items; -- 1515 / 1788 / 0
select count(*) inventory_events from public.inventory_events; -- 1550
select count(*) migration_count from supabase_migrations.schema_migrations; -- 17 after recording only new file
select version,name from supabase_migrations.schema_migrations where version='20260921220051';
select x missing_table from unnest(array['pos_private.request_limits','public.pos_access_events','pos_private.stock_permits','public.pos_workspace_settings','public.pos_location_inventory_locations','public.pos_tenders','public.pos_checkout_cancellations','public.pos_sales','public.pos_sale_items','public.pos_sale_allocations','public.pos_store_locations','public.pos_inventory_delegations','public.pos_registers','public.pos_register_sessions','public.pos_cash_events','public.pos_operation_receipts','public.pos_approval_requests','public.pos_approval_decisions','public.pos_refunds','public.pos_refund_items','pos_private.approval_uses','public.pos_payment_checkouts','public.pos_payment_refund_attempts','public.pos_payment_events','public.pos_payment_audit','pos_private.payment_test_config','pos_private.mock_payments','pos_private.mock_refunds','pos_private.payment_context','pos_private.square_connections','public.pos_payment_attempts','pos_private.square_credentials','pos_private.square_oauth','pos_private.square_locations','pos_private.square_mappings','pos_private.square_observations','pos_private.square_refund_observations','pos_private.square_events','public.pos_payment_devices','pos_private.square_device_codes','pos_private.square_terminal_attempts','pos_private.square_hardware_audit','pos_private.square_terminal_refunds']) x where to_regclass(x) is null; -- zero
select x missing_function from unnest(array['pos_private.resolve_owner_barcode(uuid,uuid,text,uuid)','pos_payment_refund_command(uuid,text,jsonb)','pos_private.resolve_barcode(uuid,uuid,text)','pos_private.refund(uuid,jsonb)','pos_private.session_transition()','pos_command(uuid,text,jsonb)','pos_private.permission(uuid,text)','pos_private.authorize(uuid,boolean,boolean)','pos_payment_command(uuid,text,jsonb)','pos_square_service(text,jsonb)','pos_square_settings(uuid,text,jsonb)','pos_private.calculate(uuid,uuid,jsonb)','pos_private.record_sale_cash()','pos_terminal_devices(uuid,text,jsonb)','pos_private.square_admin(uuid,uuid)','pos_private.terminal_busy(uuid)','pos_private.terminal_scoped(text[])','pos_private.terminal_devices(uuid)','pos_private.cost_snapshot(jsonb)','pos_private.immutable()','pos_private.payment_transition()','pos_private.payment_authorize(uuid,uuid,boolean)','pos_private.payment_view(uuid)','pos_private.expected_cash(uuid)','pos_private.permitted_stock_update(jsonb,jsonb)','pos_private.payment_audit(uuid,text,text,text)','pos_private.lock_authority(uuid,uuid,uuid,text)','pos_private.read_operations(uuid,text,jsonb)','pos_private.square_settings(uuid)','pos_private.protect_event_origin()','pos_private.protect_refund_event()','pos_private.site_access(uuid,uuid)','pos_private.access_command(uuid,text,jsonb)','pos_private.approved(uuid,uuid,text,jsonb)','pos_private.operations(uuid,text,jsonb)','pos_private.delegation_history()','pos_private.can_transact(uuid,uuid,uuid,text)','pos_private.payment_close_guard()','pos_private.payment_validate_stock(uuid,uuid,jsonb)','pos_private.check_stock()','pos_private.payment_refund_command(uuid,text,jsonb)','pos_private.terminal_attempt_guard()','pos_private.terminal_attempt_context()','pos_private.terminal_service(text,jsonb)','pos_private.payment_command(uuid,text,jsonb)','pos_provider_request_budget(uuid,text)','pos_private.cash_command(uuid,text,jsonb)','pos_private.command(uuid,text,jsonb)','pos_private.payment_refund_quote(uuid,jsonb)']) x where to_regprocedure(x) is null; -- zero
select c.oid::regclass unprotected from pg_class c where c.oid in(select to_regclass(x) from unnest(array['pos_private.request_limits','public.pos_access_events','pos_private.stock_permits','public.pos_workspace_settings','public.pos_location_inventory_locations','public.pos_tenders','public.pos_checkout_cancellations','public.pos_sales','public.pos_sale_items','public.pos_sale_allocations','public.pos_store_locations','public.pos_inventory_delegations','public.pos_registers','public.pos_register_sessions','public.pos_cash_events','public.pos_operation_receipts','public.pos_approval_requests','public.pos_approval_decisions','public.pos_refunds','public.pos_refund_items','pos_private.approval_uses','public.pos_payment_checkouts','public.pos_payment_refund_attempts','public.pos_payment_events','public.pos_payment_audit','pos_private.payment_test_config','pos_private.mock_payments','pos_private.mock_refunds','pos_private.payment_context','pos_private.square_connections','public.pos_payment_attempts','pos_private.square_credentials','pos_private.square_oauth','pos_private.square_locations','pos_private.square_mappings','pos_private.square_observations','pos_private.square_refund_observations','pos_private.square_events','public.pos_payment_devices','pos_private.square_device_codes','pos_private.square_terminal_attempts','pos_private.square_hardware_audit','pos_private.square_terminal_refunds']) x) and not c.relrowsecurity; -- zero
select x,r exposed_table from unnest(array['pos_private.request_limits','public.pos_access_events','pos_private.stock_permits','public.pos_workspace_settings','public.pos_location_inventory_locations','public.pos_tenders','public.pos_checkout_cancellations','public.pos_sales','public.pos_sale_items','public.pos_sale_allocations','public.pos_store_locations','public.pos_inventory_delegations','public.pos_registers','public.pos_register_sessions','public.pos_cash_events','public.pos_operation_receipts','public.pos_approval_requests','public.pos_approval_decisions','public.pos_refunds','public.pos_refund_items','pos_private.approval_uses','public.pos_payment_checkouts','public.pos_payment_refund_attempts','public.pos_payment_events','public.pos_payment_audit','pos_private.payment_test_config','pos_private.mock_payments','pos_private.mock_refunds','pos_private.payment_context','pos_private.square_connections','public.pos_payment_attempts','pos_private.square_credentials','pos_private.square_oauth','pos_private.square_locations','pos_private.square_mappings','pos_private.square_observations','pos_private.square_refund_observations','pos_private.square_events','public.pos_payment_devices','pos_private.square_device_codes','pos_private.square_terminal_attempts','pos_private.square_hardware_audit','pos_private.square_terminal_refunds']) x cross join unnest(array['anon','authenticated']) r where has_table_privilege(r,x,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'); -- zero
select p.oid::regprocedure exposed_private_rpc from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('pos_private','inventory_private') and (has_function_privilege('anon',p.oid,'EXECUTE') or has_function_privilege('authenticated',p.oid,'EXECUTE')); -- zero
select has_function_privilege('anon','public.pos_square_service(text,jsonb)','EXECUTE') or has_function_privilege('authenticated','public.pos_square_service(text,jsonb)','EXECUTE') exposed_square_service; -- false
select count(*) from public.pos_workspace_settings where enabled; -- zero
select (select count(*) from pos_private.square_credentials) credentials,(select count(*) from pos_private.square_connections) connections,(select count(*) from public.pos_payment_devices) devices; -- all zero
select conrelid::regclass,conname from pg_constraint where conrelid in(select to_regclass(x) from unnest(array['pos_private.request_limits','public.pos_access_events','pos_private.stock_permits','public.pos_workspace_settings','public.pos_location_inventory_locations','public.pos_tenders','public.pos_checkout_cancellations','public.pos_sales','public.pos_sale_items','public.pos_sale_allocations','public.pos_store_locations','public.pos_inventory_delegations','public.pos_registers','public.pos_register_sessions','public.pos_cash_events','public.pos_operation_receipts','public.pos_approval_requests','public.pos_approval_decisions','public.pos_refunds','public.pos_refund_items','pos_private.approval_uses','public.pos_payment_checkouts','public.pos_payment_refund_attempts','public.pos_payment_events','public.pos_payment_audit','pos_private.payment_test_config','pos_private.mock_payments','pos_private.mock_refunds','pos_private.payment_context','pos_private.square_connections','public.pos_payment_attempts','pos_private.square_credentials','pos_private.square_oauth','pos_private.square_locations','pos_private.square_mappings','pos_private.square_observations','pos_private.square_refund_observations','pos_private.square_events','public.pos_payment_devices','pos_private.square_device_codes','pos_private.square_terminal_attempts','pos_private.square_hardware_audit','pos_private.square_terminal_refunds']) x) and not convalidated; -- zero
select indexrelid::regclass from pg_index where indrelid in(select to_regclass(x) from unnest(array['pos_private.request_limits','public.pos_access_events','pos_private.stock_permits','public.pos_workspace_settings','public.pos_location_inventory_locations','public.pos_tenders','public.pos_checkout_cancellations','public.pos_sales','public.pos_sale_items','public.pos_sale_allocations','public.pos_store_locations','public.pos_inventory_delegations','public.pos_registers','public.pos_register_sessions','public.pos_cash_events','public.pos_operation_receipts','public.pos_approval_requests','public.pos_approval_decisions','public.pos_refunds','public.pos_refund_items','pos_private.approval_uses','public.pos_payment_checkouts','public.pos_payment_refund_attempts','public.pos_payment_events','public.pos_payment_audit','pos_private.payment_test_config','pos_private.mock_payments','pos_private.mock_refunds','pos_private.payment_context','pos_private.square_connections','public.pos_payment_attempts','pos_private.square_credentials','pos_private.square_oauth','pos_private.square_locations','pos_private.square_mappings','pos_private.square_observations','pos_private.square_refund_observations','pos_private.square_events','public.pos_payment_devices','pos_private.square_device_codes','pos_private.square_terminal_attempts','pos_private.square_hardware_audit','pos_private.square_terminal_refunds']) x) and not indisvalid; -- zero
select tgname,tgenabled from pg_trigger where tgname in('a_inventory_workspace_at_write','a_chaos_workspace_at_write','pos_stock_item','pos_stock_position','pos_stock_allocation'); -- five O
commit;
-- Compare all pre-existing row hashes/owners/quantities/workspaces/events/allocations before commit.
-- Compare catalog against exact new-object manifest; only collector stock hook may differ.
-- For use inside an existing transaction, omit this script's BEGIN and COMMIT lines.
